<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Ryan James J. Martinez - Ordinal Regression Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Ryan James J. Martinez</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../projects/index.html" rel="" target="">
 <span class="menu-text">Projects</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.facebook.com/profile.php?id=100074061859253" rel="" target=""><i class="bi bi-facebook" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="mailto:martinezryanjames08@gmail.com" rel="" target=""><i class="bi bi-envelope" role="img" aria-label="email">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#ordinal-logistic-regression" id="toc-ordinal-logistic-regression" class="nav-link" data-scroll-target="#ordinal-logistic-regression">Ordinal Logistic Regression</a>
  <ul class="collapse">
  <li><a href="#background" id="toc-background" class="nav-link" data-scroll-target="#background">Background</a></li>
  <li><a href="#motivation-of-the-study" id="toc-motivation-of-the-study" class="nav-link" data-scroll-target="#motivation-of-the-study">Motivation of the study</a></li>
  <li><a href="#regression-model" id="toc-regression-model" class="nav-link" data-scroll-target="#regression-model">Regression Model</a></li>
  <li><a href="#assumptions" id="toc-assumptions" class="nav-link" data-scroll-target="#assumptions">Assumptions</a></li>
  </ul></li>
  <li><a href="#model-evaluation-and-diagnostics" id="toc-model-evaluation-and-diagnostics" class="nav-link" data-scroll-target="#model-evaluation-and-diagnostics">Model Evaluation and Diagnostics</a>
  <ul class="collapse">
  <li><a href="#pseudo-r-squared" id="toc-pseudo-r-squared" class="nav-link" data-scroll-target="#pseudo-r-squared">Pseudo R-squared</a></li>
  <li><a href="#likelihood-ratio-test" id="toc-likelihood-ratio-test" class="nav-link" data-scroll-target="#likelihood-ratio-test">Likelihood Ratio Test</a></li>
  <li><a href="#lipsitz-test" id="toc-lipsitz-test" class="nav-link" data-scroll-target="#lipsitz-test">Lipsitz Test</a></li>
  <li><a href="#accuracy" id="toc-accuracy" class="nav-link" data-scroll-target="#accuracy">Accuracy</a></li>
  <li><a href="#sensitivity-and-specificity" id="toc-sensitivity-and-specificity" class="nav-link" data-scroll-target="#sensitivity-and-specificity">Sensitivity and Specificity</a></li>
  <li><a href="#bootstrapping" id="toc-bootstrapping" class="nav-link" data-scroll-target="#bootstrapping">Bootstrapping</a></li>
  </ul></li>
  <li><a href="#implementation-in-r" id="toc-implementation-in-r" class="nav-link" data-scroll-target="#implementation-in-r">Implementation in R</a>
  <ul class="collapse">
  <li><a href="#example-1" id="toc-example-1" class="nav-link" data-scroll-target="#example-1">Example 1</a></li>
  <li><a href="#descriptive-statistics" id="toc-descriptive-statistics" class="nav-link" data-scroll-target="#descriptive-statistics">Descriptive Statistics</a></li>
  <li><a href="#checking-assumptions" id="toc-checking-assumptions" class="nav-link" data-scroll-target="#checking-assumptions">Checking Assumptions</a></li>
  <li><a href="#modeling" id="toc-modeling" class="nav-link" data-scroll-target="#modeling">Modeling</a></li>
  <li><a href="#assessment-of-model-fit" id="toc-assessment-of-model-fit" class="nav-link" data-scroll-target="#assessment-of-model-fit">Assessment of Model Fit</a></li>
  <li><a href="#removing-insignificant-variable" id="toc-removing-insignificant-variable" class="nav-link" data-scroll-target="#removing-insignificant-variable">Removing Insignificant Variable</a></li>
  <li><a href="#modeling-1" id="toc-modeling-1" class="nav-link" data-scroll-target="#modeling-1">Modeling</a></li>
  <li><a href="#example-2" id="toc-example-2" class="nav-link" data-scroll-target="#example-2">Example 2</a></li>
  <li><a href="#exploratory-data-analysis" id="toc-exploratory-data-analysis" class="nav-link" data-scroll-target="#exploratory-data-analysis">Exploratory Data Analysis</a></li>
  <li><a href="#checking-assumptions-1" id="toc-checking-assumptions-1" class="nav-link" data-scroll-target="#checking-assumptions-1">Checking Assumptions</a></li>
  <li><a href="#modeling-2" id="toc-modeling-2" class="nav-link" data-scroll-target="#modeling-2">Modeling</a></li>
  <li><a href="#assessing-of-model-fit" id="toc-assessing-of-model-fit" class="nav-link" data-scroll-target="#assessing-of-model-fit">Assessing of Model Fit</a></li>
  <li><a href="#removing-insignificant-variable-1" id="toc-removing-insignificant-variable-1" class="nav-link" data-scroll-target="#removing-insignificant-variable-1">Removing Insignificant Variable</a></li>
  <li><a href="#modeling-3" id="toc-modeling-3" class="nav-link" data-scroll-target="#modeling-3">Modeling</a></li>
  </ul></li>
  <li><a href="#conclusion-and-recommendation" id="toc-conclusion-and-recommendation" class="nav-link" data-scroll-target="#conclusion-and-recommendation">Conclusion and Recommendation</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Ordinal Regression Analysis</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>Ordinal outcomes are common in research studies and real-world applications. These outcomes are not binary and instead fall into multiple ordered categories. It is essential to understand and model such outcomes for decision-making purposes.</p>
<p>To analyze and model the relationships between one or more predictor variables and an ordinal response variable, statisticians use ordinal logistic regression. This statistical model is an extension of logistic regression, which can handle the dependent variable with two or more ordered categories. On the other hand, multinomial logistic regression is an extended version of binary logistic regression. However, it does not preserve the ranking information in the dependent variable when returning the information on the contribution of each independent variable.</p>
<p>The difference in response scales might require different equations to model them correctly. For example, the ordered scale needs a different function than the unordered scale. In the case of the ordered scale, it is more useful to work with cumulative probabilities (McCullagh and Nelder, 1989). For instance, the cumulative probability of “agreeing” includes the probabilities of “agreeing” and “strongly agreeing” combined. However, this approach only makes sense if the order of categories is clear.</p>
</section>
<section id="ordinal-logistic-regression" class="level1">
<h1>Ordinal Logistic Regression</h1>
<section id="background" class="level3">
<h3 class="anchored" data-anchor-id="background">Background</h3>
<p><strong>Peter McCullagh</strong> - A Northern Irish-born American statistician. Distinguished Service Professor in the Department of Statistics at the University of Chicago.</p>
<ul>
<li>Thesis - Analysis of Ordered Categorical Data (1977)</li>
</ul>
</section>
<section id="motivation-of-the-study" class="level3">
<h3 class="anchored" data-anchor-id="motivation-of-the-study">Motivation of the study</h3>
<p>McCullagh’s motivation for the ordinal model is to develop statistical methods that even after combining levels of responses, the validity of conclusion will not be affected by the new number of responses. The amalgamation of the response categories in this way will normally reduce the available information, change the estimate, the attained significance level and so on. The important point is that the same parameter is being measured however many categories are combined (McCullagh, 1980)</p>
</section>
<section id="regression-model" class="level3">
<h3 class="anchored" data-anchor-id="regression-model">Regression Model</h3>
<p>Let <span class="math inline">\(Y\)</span> denote the ordered response with <span class="math inline">\(k\)</span> categories, with <span class="math inline">\(k \geq 3\)</span>. Then <span class="math inline">\(P(Y \leq j)\)</span> is the cumulative probability of <span class="math inline">\(Y\)</span> less than or equal to a specific category <span class="math inline">\(j = 1, ..., k-1\)</span>.</p>
<p>The model can be defined as <span class="math display">\[log\left\{\frac{P(Y \leq j)}{P(Y &gt; j)}\right\} = logit(P(Y \leq j)) = \beta_{j0} - \beta_{1}X_{1} - \cdots - \beta_{p}X_{p}\]</span> where <span class="math inline">\(j = 1,...,k-1\)</span></p>
<p><strong>Remark</strong>: If <span class="math inline">\(k = 2\)</span>, however ordered nature the dependent variable is, the model is the same as binary logistic regression.</p>
</section>
<section id="assumptions" class="level3">
<h3 class="anchored" data-anchor-id="assumptions">Assumptions</h3>
<p>The assumptions of the Ordinal Logistic Regression are as follow:</p>
<ol type="1">
<li>The dependent variable is ordered.</li>
<li>One or more of the independent variables are either continuous, categorical or ordinal.</li>
<li>No zero cell count.</li>
<li>No multicollinearity.</li>
<li>Parallel Regression Lines</li>
</ol>
<p>The data of the dependent variable must be ordinal in nature to best explain the outcome of the model.</p>
<p>Ordinal logistic regression works if the independent variable is only continuous, categorical, or ordinal. If there are several independent variable, the model also works if all of it are only continuous, only categorical, or only ordinal.</p>
<p>The frequency of each of the category of the dependent variable must not be zero. Furthermore, it is also suggested if each category has equal count since if an event of greater cell with less count occurs,, the less reliable the chi-square test will be.</p>
<p>The regression model also assumes that the effect of the independent variable/s is the same for all categories of the dependent variable. This assumption is called the proportional odds, parallel lines, parallel slopes, or parallel regression assumption (Borooah, 2002; Hardin &amp; Hilbe, 2007; Long, 1997), and this will be referred as the parallel lines assumption.</p>
</section>
</section>
<section id="model-evaluation-and-diagnostics" class="level1">
<h1>Model Evaluation and Diagnostics</h1>
<p>Assessing model fit is the process of checking whether the model fits the data sufficiently well. The methods of assessment are the following:</p>
<section id="pseudo-r-squared" class="level3">
<h3 class="anchored" data-anchor-id="pseudo-r-squared">Pseudo R-squared</h3>
<p>In linear regression, the coefficient of determination, <span class="math inline">\(R^2\)</span>, measures the variance in the dependent variable explained by the predictors, with higher <span class="math inline">\(R^2\)</span> values (up to a maximum of 1) indicating a better explanatory fit of the model. For regression models with categorical dependent variables, calculating a direct <span class="math inline">\(R^2\)</span> similar to that in linear models is unfeasible. Instead, approximations of <span class="math inline">\(R^2\)</span> are used to estimate the model’s explanatory power, adapting the concept to fit the context of categorical outcomes (IBM, 2023). For this assessment, there are three values of <span class="math inline">\(R^2\)</span>, each of which have different formulas. The following are the three different <span class="math inline">\(R^2\)</span>:</p>
<p><span class="math display">\[R^2_{\text{McF}} = 1 - \frac{\log(L_M)}{\log(L_0)}\]</span> <span class="math display">\[R^2_{\text{CS}} = 1 - \left(\frac{L_0}{L_M}\right)^{2/n}\]</span> <span class="math display">\[R^2_{\text{Nagelkerke}} = \frac{1 - \left(\frac{L_0}{L_M}\right)^{2/n}}{1 - L_0^{2/n}}\]</span> where <span class="math inline">\(L_M\)</span> is the fitted model, <span class="math inline">\(L_0\)</span> is the null model, <span class="math inline">\(n\)</span> is the sample size.</p>
<ul>
<li><p><span class="math inline">\(R^2_{\text{McF}}\)</span> is McFadden’s version of pseudo <span class="math inline">\(R^2\)</span>, based on the log-likelihood kernels for the intercept-only model and the full estimated model (McFadden, 1974).</p></li>
<li><p>Cox and Snell’s <span class="math inline">\(R^2_{\text{CS}}\)</span> is based on the log likelihood for the model compared to the log-likelihood for a baseline model (Cox and Snell 1989).</p></li>
<li><p>Nagelkerke’s <span class="math inline">\(R^2_{\text{Nagelkerke}}\)</span> is an adjusted version of the Cox and Snell <span class="math inline">\(R^2\)</span> that adjusts the scale of the statistic to cover the full range from 0 to 1 (Nagelkerke, 1991).</p></li>
</ul>
<p>The category of the the values of <span class="math inline">\(R^2\)</span> can be summarized as follows:</p>
<ul>
<li>0 to 0.2: Weak fit</li>
<li>0.2 to 0.4: Moderate fit</li>
<li>0.4 to 0.6: Good fit</li>
<li>0.6 to 0.8: Very good fit</li>
<li>0.8 to 1: Excellent fit</li>
</ul>
</section>
<section id="likelihood-ratio-test" class="level3">
<h3 class="anchored" data-anchor-id="likelihood-ratio-test">Likelihood Ratio Test</h3>
<p>The likelihood ratio test compares the likelihoods of these two models to determine whether the additional parameters in the full model significantly improve the fit compared to the reduced model. The null hypothesis of the test is the simpler model (reduced model) is sufficient to explain the data. There is no significant improvement in model fit when adding extra parameters. The alternative hypothesis is the more complex model (full model) provides a significantly better fit to the data than the simpler model. This test is calculated as the ratio of the likelihood of the full model to the likelihood of the reduced model. Mathematically, it is represented as: <span class="math display">\[LR = -2 * (\text{log likelihood of reduced model} - \text{log likelihood of full model})\]</span></p>
</section>
<section id="lipsitz-test" class="level3">
<h3 class="anchored" data-anchor-id="lipsitz-test">Lipsitz Test</h3>
<p>The Lipsitz test checks if your model fits the real data well. In other words, it sees if the predictions your model makes is the same about the actual data. The test compares what your model predicts (expected probabilities) with what actually occurs (observed frequencies). If your model is good, the predictions and actual outcomes should be pretty close. The null hypothesis of this test is that the frequencies of the ordinal response variable are consistent with the expected frequencies predicted by the model (Lipsitz, et al., 1996).</p>
</section>
<section id="accuracy" class="level3">
<h3 class="anchored" data-anchor-id="accuracy">Accuracy</h3>
<p>Accuracy is one metric for evaluating classification models. It is the measurement used to determine which model is best at identifying relationships and patterns between variables in a dataset. Accuracy follows the definition:</p>
<p><span class="math display">\[\text{Accuracy} = \frac{\text{Number of correct predictions}}{\text{Total number of predictions}}\]</span></p>
<p>Where the <code>number of correct predictions</code>, as the name implies, are the accurate predicted values by the model, and the <code>total number of predictions</code> are the total observations in the validation set.</p>
</section>
<section id="sensitivity-and-specificity" class="level3">
<h3 class="anchored" data-anchor-id="sensitivity-and-specificity">Sensitivity and Specificity</h3>
<p>Sensitivity is the metric that evaluates a model’s ability to predict true positives of each available category. Specificity is the metric that evaluates a model’s ability to predict true negatives of each available category (Mitrani, A., 2019). The equations below are for calculating sensitivity and specificity:</p>
<p><span class="math display">\[\text{Sensitivity} = \frac{\text{True Positives}}{\text{True Positives + False Negatives}}\]</span></p>
<p><span class="math display">\[\text{Specificity} = \frac{\text{True Negatives}}{\text{True Negatives + False Positives}}\]</span></p>
<p>Where <code>true positives</code> are the number of observations the model predicted were positive that were actually positive. While <code>false negatives</code> are the number of observations the model predicted were positive that were actually negative. Moreover, <code>false negatives</code>, are the number of observations the model predicted were negative that were actually positive. Lastly, <code>true negatives</code> are the number of observations the model predicted were negative that were actually negative.</p>
</section>
<section id="bootstrapping" class="level3">
<h3 class="anchored" data-anchor-id="bootstrapping">Bootstrapping</h3>
<p>Bootstrapping is a statistical technique used to estimate the sampling distribution of an estimator by resampling with replacement from the original data. This is often used when the theoretical distribution of an estimator is complex or unknown. This method involves repeatedly drawing samples, typically thousands of times, from the data set and calculating the statistic of interest for each sample. The bootstrap method allows for the estimation of standard errors, confidence intervals, and significance tests, which are critical in many statistical analyses (Efron and Tibshirani, 1994).</p>
<p>Bootstrapping does not rely on the assumptions of normality and can be applied to complex, skewed, or small datasets where other methods might fail or provide biased estimates (Davison and Hinkley, 1997). It offers a straightforward way to derive robust estimates of standard errors and confidence intervals for complex estimators or models without needing explicit formulas.</p>
</section>
</section>
<section id="implementation-in-r" class="level1">
<h1>Implementation in R</h1>
<section id="example-1" class="level3">
<h3 class="anchored" data-anchor-id="example-1">Example 1</h3>
<p>A study looks at factors that influence the decision of whether to apply to graduate school. College juniors are asked if they are unlikely, somewhat likely, or very likely to apply to graduate school. Data on parental educational, a binary variable indicating if at least one parent has attended graduate school and whether the undergraduate institution is public or private, and the current GPA of the student is also collected. The researchers have reason to believe that the “distances” between these three points are not equal. For example, the “distance” between “unlikely” and “somewhat likely” may be shorter than the distance between “somewhat likely” and “very likely”.<br>
</p>
<p><strong>Feature Description</strong></p>
<ul>
<li><p><strong>apply</strong> (Dependent Variable) - The apply variable is an ordered categorical variable with responses to a survey about whether a student feels they are “Unlikely” (1), “Somewhat likely” (2), or “Very likely” (3) to apply to graduate school.</p></li>
<li><p><strong>parental education status variable</strong> or <strong>pared</strong> - The pared variable is a binary variable indicating if at least one parent has attended graduate school. 1 - at least one parent has a graduate degree; 0 otherwise</p></li>
<li><p><strong>public</strong> - The public variable is a binary variable indicating if the undergraduate institution is public (as opposed to private); 1- public; 0-private</p></li>
<li><p><strong>gpa</strong> - gpa variable is the student’s grade point average (1-4)</p></li>
</ul>
<p><strong>Goal</strong></p>
<p>To quantitatively assess the influence of various factors on the likelihood that a student will decide to apply to graduate school(moving from being “unlikely” to “somewhat likely,” or from “somewhat likely” to “very likely”).</p>
<p><strong>Partitioning</strong></p>
<p>The data is split into partition with <span class="math inline">\(80\%\)</span> falls in the training data, while the remaining <span class="math inline">\(20\%\)</span> is for the testing data. This partitioning approach ensures that the model is trained on a substantial portion of the data. This allows it to learn the underlying patterns of the data effectively. Meanwhile, the testing data provides an unbiased assessment of the model’s performance on unseen data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>training_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"training_data.csv"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>testing_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"testing_data.csv"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste0</span>(<span class="st">"Training Data: "</span>, <span class="fu">nrow</span>(training_data), </span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>             <span class="st">"; Testing Data: "</span>, <span class="fu">nrow</span>(testing_data)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Training Data: 400; Testing Data: 100"</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">head</span>(training_data), </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">caption =</span> <span class="st">"First Six Rows of the Example 1 Data."</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>First Six Rows of the Example 1 Data.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">apply</th>
<th style="text-align: right;">pared</th>
<th style="text-align: right;">public</th>
<th style="text-align: right;">gpa</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">very likely</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3.26</td>
</tr>
<tr class="even">
<td style="text-align: left;">somewhat likely</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3.21</td>
</tr>
<tr class="odd">
<td style="text-align: left;">unlikely</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3.94</td>
</tr>
<tr class="even">
<td style="text-align: left;">somewhat likely</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2.81</td>
</tr>
<tr class="odd">
<td style="text-align: left;">somewhat likely</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2.53</td>
</tr>
<tr class="even">
<td style="text-align: left;">unlikely</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2.59</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="descriptive-statistics" class="level3">
<h3 class="anchored" data-anchor-id="descriptive-statistics">Descriptive Statistics</h3>
<p>Descriptive statistics provides basic information about the features of the data. In this way, it offers a clear overview of the data distribution and central tendencies. This analysis is crucial for identifying trends, spotting anomalies, and laying the groundwork for statistical examinations.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Checking for Missing values</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(training_data, <span class="cf">function</span>(x) <span class="fu">sum</span>(<span class="fu">is.na</span>(x)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> apply  pared public    gpa 
     0      0      0      0 </code></pre>
</div>
</div>
<p>The code snippet above sums the number of missing values in each of the variables. The result obtained shows that there are no missing values in any of the four variables. Therefore, there is no need to take any further steps to handle any missing data. Next, the distribution of categorical variables will be examined to determine if there is any imbalance present.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(training_data[, <span class="fu">c</span>(<span class="st">"apply"</span>, <span class="st">"pared"</span>, <span class="st">"public"</span>)], table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$apply

somewhat likely        unlikely     very likely 
            140             220              40 

$pared

  0   1 
337  63 

$public

  0   1 
343  57 </code></pre>
</div>
</div>
<p>The concept of the code above counts the number of categories in each of the variables. In the apply variable, the unlikely holds the majority of the counts. Furthermore, the distribution of the frequency suggests that they are not equal or approximately equal. A possible consequence of this is that when modeling, the fitted model may not perform well in prediction. For the pared and public variables, there is an imbalance in the values, the majority of the counts are zero. Again, a possible consequence of this phenomenon is that the model may not perform well in forecasting.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ftable</span>(<span class="fu">xtabs</span>(<span class="sc">~</span> public <span class="sc">+</span> apply <span class="sc">+</span> pared, <span class="at">data =</span> training_data))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                       pared   0   1
public apply                        
0      somewhat likely        98  26
       unlikely              175  14
       very likely            20  10
1      somewhat likely        12   4
       unlikely               25   6
       very likely             7   3</code></pre>
</div>
</div>
<p>It shows the frequency counts of respondents classified by their likelihood of applying—categorized as “somewhat likely,” “unlikely,” and “very likely”—across combinations of two binary conditions: public (0 or 1) and pared (0 or 1). For instance, under the <code>public</code> = 0 category, 98 respondents are “somewhat likely” to apply when pared is 0, and 26 are “somewhat likely” when <code>pared</code> is 1. The table indicates that the majority of respondents, especially when <code>public</code> is 0, are “unlikely” to apply. It is also noticeable that there is unequal in the frequency in the different categories of <code>apply</code> variable. This phenomenon can significantly impact the accuracy and performance of the model. If certain categories are dominant over the others, it could skew the model’s ability to accurately estimate relationships between less frequent categories. Furthermore, it may not provide enough data to accurately estimate the model.</p>
<p>Checking outliers in regression analysis is crucial as the presence of it may affect the performance of the model. One of the ways for checking the presence of the event is by performing boxplots. </p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="ordered_logit_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption class="figure-caption">Boxplot of public and pared variable</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="ordered_logit_files/figure-html/unnamed-chunk-7-2.png" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption class="figure-caption">Boxplot of public and pared variable</figcaption>
</figure>
</div>
</div>
</div>
<p>The boxplots above compares the distributions og <code>gpa</code> based on <code>public</code> and <code>pared</code> variables. From the two boxplots, there is existence of outliers in the data points, this is represented as the points that deviate outside the whiskers. However, there are only small portion of it, hence, the modeling can proceed at ease. While at it, we might as well explain the distribution of the boxplots. The distribution of <code>gpa</code> does not show dramatic differences between the categories within each condition (0 and 1). However, for condition 1—public—students who are “very likely” to apply seem to have a slightly higher median GPA compared to the other categories. For the <code>pared</code>, the distribution of <code>gpa</code> are somewhat consistent across categories, but there is a noticeable shift in medians. For condition 0, students who are “unlikely” to apply tend to have lower GPA medians. For condition 1, students who are “very likely” to apply have noticeably higher GPA.</p>
<p>The nature of the data now is transformed into factor to be fitted by ordinal logistic regressions. The code snippet below simply do the virtue of transformation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>training_data<span class="sc">$</span>apply <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(training_data<span class="sc">$</span>apply <span class="sc">==</span> <span class="st">"unlikely"</span>, <span class="dv">1</span>, </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>                       <span class="fu">ifelse</span>(training_data<span class="sc">$</span>apply <span class="sc">==</span> <span class="st">"somewhat likely"</span>, <span class="dv">2</span>, <span class="dv">3</span>))</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>training_data<span class="sc">$</span>apply <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(training_data<span class="sc">$</span>apply)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>training_data<span class="sc">$</span>pared <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(training_data<span class="sc">$</span>pared)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>training_data<span class="sc">$</span>public <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(training_data<span class="sc">$</span>public)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(training_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   400 obs. of  4 variables:
 $ apply : Factor w/ 3 levels "1","2","3": 3 2 1 2 2 1 2 2 1 2 ...
 $ pared : Factor w/ 2 levels "0","1": 1 2 2 1 1 1 1 1 1 2 ...
 $ public: Factor w/ 2 levels "0","1": 1 1 2 1 1 2 1 1 1 1 ...
 $ gpa   : num  3.26 3.21 3.94 2.81 2.53 ...</code></pre>
</div>
</div>
</section>
<section id="checking-assumptions" class="level3">
<h3 class="anchored" data-anchor-id="checking-assumptions">Checking Assumptions</h3>
<p>In the descriptive statistics performed earlier, it is evident that the nature of the dependent variable is ordinal and has three categories in fact(<code>Unlikely</code>, <code>Somewhat Likely</code>, <code>Very likely</code>). The independent variables also are continuous (<code>gpa</code>), categorical(<code>pared</code> and <code>public</code>). There is no zero count phenomenon in each of the category of the dependent variable.</p>
<p><strong>Checking the Presence of Multicollinearity</strong></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggpairs</span>(training_data[, <span class="sc">-</span><span class="dv">1</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="ordered_logit_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption class="figure-caption">Correlation Assumption</figcaption>
</figure>
</div>
</div>
</div>
<p>No multicollinearity appeared since the data only have one continuous independent variable. Notice that, there is a clear image of disproportions in the frequency of <code>pared</code> and <code>public</code>.</p>
<p><strong>Checking Parallel Regression Lines</strong></p>
<p>The assumption parallel regression lines can be checked using Brant’s test. It is a parallel lines assumption at which the effect of the independent variable is the same for all categories of the dependent variable (Arfan and Sherwani, 2017, p.212). In other words, parallel lines assumption means that the correlation between dependent and independent variable does not change for the categories of dependent variable, and thus, to test the unchangeability of the parameter estimates at cut-off points (Arı and Yıldız, 2014, p.10).</p>
<p>If violated, we can still perform the model but be cautious in interpreting the results because the estimated coefficients may not fully capture the relationship between the predictor variables and the ordinal response variable if the assumption of parallel regression lines is violated.</p>
<p>The null hypothesis of the test is that the parallel regression assumption holds, while the alternative is it does not hold. The said test can be done in <code>R</code> using the <code>brant()</code> function in package. To perform the test, it requires to fit an ordinal logistic regression model first using the <code>polr()</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Modeling</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>prop.odds <span class="ot">&lt;-</span> <span class="fu">polr</span>(apply <span class="sc">~</span> pared <span class="sc">+</span> public <span class="sc">+</span> gpa, <span class="at">data =</span> training_data)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Brant's Test</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="fu">brant</span>(prop.odds)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>-------------------------------------------- 
Test for    X2  df  probability 
-------------------------------------------- 
Omnibus     4.34    3   0.23
pared1      0.13    1   0.72
public1     3.44    1   0.06
gpa     0.18    1   0.67
-------------------------------------------- 

H0: Parallel Regression Assumption holds</code></pre>
</div>
</div>
<p>The output of the <code>brant()</code> function contains four columns, particularly, test for the variable, the <span class="math inline">\(\chi^2\)</span>, the <code>df</code>, and the probability or the <code>p-value</code>. Notice that, there are only three independent variables, but an additional variable appeared in the output, the <code>Omnibus</code>. The <code>Omnibus</code> variable is the global assessment of the assumption. The p-values for all variables are greater than 0.05, hence, the proportional odds assumption holds</p>
<p>Now, the checking of assumptions is done, and none are violated, albeit there is the presence of an imbalance in the frequencies of the categorical variables. Nevertheless, the next thing to perform is to proceed with the modeling part of the ordinal logistic regression in the following subsection.</p>
</section>
<section id="modeling" class="level3">
<h3 class="anchored" data-anchor-id="modeling">Modeling</h3>
<p>To model ordinal logistic regression in <code>R</code>, the function <code>polr()</code> does the honors as mentioned earlier. However, this time, the <code>Hess</code> parameter is added and set to <code>TRUE</code> to perform the Hessian matrix in the model. The Hessian matrix, also known as the Hessian or the Hessian matrix of second partial derivatives, is a square matrix of second-order partial derivatives of a scalar-valued function. In the context of logistic regression, the Hessian matrix is used to calculate standard errors, test statistics, and confidence intervals for the estimated coefficients (parameters) of the model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">polr</span>(apply <span class="sc">~</span> pared <span class="sc">+</span> public <span class="sc">+</span> gpa, <span class="at">data =</span> training_data, <span class="at">Hess =</span> <span class="cn">TRUE</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
polr(formula = apply ~ pared + public + gpa, data = training_data, 
    Hess = TRUE)

Coefficients:
           Value Std. Error t value
pared1   1.04769     0.2658  3.9418
public1 -0.05879     0.2979 -0.1974
gpa      0.61594     0.2606  2.3632

Intercepts:
    Value   Std. Error t value
1|2  2.2039  0.7795     2.8272
2|3  4.2994  0.8043     5.3453

Residual Deviance: 717.0249 
AIC: 727.0249 </code></pre>
</div>
</div>
<p>After checking the summary of the model using the <code>summary()</code> function, it provides the coefficients, intercepts, residual deviance, and AIC. Notice that in the coefficient and intercepts part, there is no p-value of the output. This is hard to interpret as we cannot determine which of which is statistically significant. Hence, before interpreting, the calculation of the p-value ought to be performed first. The codes below do the virtue of performing what is needed.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>coefs <span class="ot">&lt;-</span> <span class="fu">coef</span>(<span class="fu">summary</span>(fit))</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate P-value</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">pnorm</span>(<span class="fu">abs</span>(coefs[, <span class="st">"t value"</span>]), <span class="at">lower.tail =</span> <span class="cn">FALSE</span>) <span class="sc">*</span> <span class="dv">2</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Add Column</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>coefs <span class="ot">&lt;-</span> <span class="fu">cbind</span>(coefs, <span class="st">"p value"</span> <span class="ot">=</span> p) </span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">round</span>(coefs, <span class="dv">4</span>), <span class="at">caption =</span> <span class="st">"Coefficients and Intercepts"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Coefficients and Intercepts</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Value</th>
<th style="text-align: right;">Std. Error</th>
<th style="text-align: right;">t value</th>
<th style="text-align: right;">p value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">pared1</td>
<td style="text-align: right;">1.0477</td>
<td style="text-align: right;">0.2658</td>
<td style="text-align: right;">3.9418</td>
<td style="text-align: right;">0.0001</td>
</tr>
<tr class="even">
<td style="text-align: left;">public1</td>
<td style="text-align: right;">-0.0588</td>
<td style="text-align: right;">0.2979</td>
<td style="text-align: right;">-0.1974</td>
<td style="text-align: right;">0.8435</td>
</tr>
<tr class="odd">
<td style="text-align: left;">gpa</td>
<td style="text-align: right;">0.6159</td>
<td style="text-align: right;">0.2606</td>
<td style="text-align: right;">2.3632</td>
<td style="text-align: right;">0.0181</td>
</tr>
<tr class="even">
<td style="text-align: left;">1|2</td>
<td style="text-align: right;">2.2039</td>
<td style="text-align: right;">0.7795</td>
<td style="text-align: right;">2.8272</td>
<td style="text-align: right;">0.0047</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2|3</td>
<td style="text-align: right;">4.2994</td>
<td style="text-align: right;">0.8043</td>
<td style="text-align: right;">5.3453</td>
<td style="text-align: right;">0.0000</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Now, from the table above, the estimated model can be written as:</p>
<p><span class="math display">\[logit(\hat{P}(Y \leq 1) = 2.20 - 1.05*\textbf{pared} - (-0.6)*\textbf{public} - 0.62*\textbf{gpa}\]</span> <span class="math display">\[logit(\hat{P}(Y \leq 2) = 4.30 - 1.05*\textbf{pared} - (-0.6)*\textbf{public} - 0.62*\textbf{gpa}\]</span></p>
<p><strong>Interpretation</strong></p>
<p>The last two rows in the coefficients and intercepts table are the intercepts, or cutpoints, of the Ordinal Logistic Regression. These cutpoints indicate where the latent variable is cut to make the three groups that are observed in the data. The <code>public1</code> is the only variable that is not statistically significant since its p-value is greater than <span class="math inline">\(0.05\)</span>. The rest of the independent variable, and the intercepts are significant at the arbitrary <span class="math inline">\(0.05\)</span> alpha value.</p>
<p>Coefficients:</p>
<p><strong>pared (Parental Education Status)</strong>: Holding all other variables constant, if a student’s parent has attended graduate school (pared = 1) rather than not (pared = 0), the log-odds of the student being in a higher category (e.g., from “Unlikely” to “Somewhat likely”, or from “Somewhat likely” to “Very likely”) of applying to graduate school increase by approximately 1.05 units. Students whose parents have higher educational attainments are more likely to pursue and succeed in higher education themselves. This phenomenon is often attributed to the social and cultural capital that educated parents pass on to their children, which influences their educational aspirations and achievements (Perna and Titus, 2005).</p>
<p><strong>public (Institution Type)</strong>: Holding all other variables constant, there is no statistically significant effect of whether the undergraduate institution is public (public = 1) or private (public = 0) on the log-odds of a student being in a higher category of likelihood to apply to graduate school. Research by Bowen and Bok (1998) in their book “The Shape of the River” highlights that the type of undergraduate institution (public vs.&nbsp;private) does not significantly impact the subsequent success in graduate education, suggesting that factors like individual achievement and socioeconomic status might play more significant roles.</p>
<p><strong>gpa</strong>: Holding all other variables constant, for every one-unit increase in GPA, the log-odds of a student being in a higher category of likelihood to apply to graduate school increase by approximately 0.62 units. A study by Ethington and Smart (1986) indicates that GPA is a strong predictor of graduate school enrollment, reflecting academic preparedness and motivation, which are critical in higher education pursuits.</p>
<p>Intercepts:</p>
<p><strong>Transition from “Unlikely” to “Somewhat likely”</strong>: Holding all other variables constant, the log-odds of a student transitioning from feeling “Unlikely” to “Somewhat likely” to apply to graduate school increase by approximately 2.20 units. This is supported by Tinto’s Theory of Student Departure (1993) which can provide a basis for understanding how certain thresholds or transitions in educational decision-making are influenced by previous educational experiences and integration within the academic system.</p>
<p><strong>Transition from “Somewhat likely” to “Very likely”</strong>: Holding all other variables constant, the log-odds of a student transitioning from feeling “Somewhat likely” to “Very likely” to apply to graduate school increase by approximately 4.30 units. According to Astin’s Theory of Involvement (1984), it argues that the degree of student involvement in academic and extracurricular activities significantly influences their commitment to educational goals, such as applying to graduate school.</p>
<p><strong>Confidence Interval</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>ci <span class="ot">&lt;-</span> <span class="fu">confint</span>(fit, <span class="at">level =</span> <span class="fl">0.95</span>)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">cbind</span>(<span class="at">logit =</span> <span class="fu">coef</span>(fit), ci), </span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">caption =</span> <span class="st">"Condidence Interval of Logit"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Condidence Interval of Logit</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">logit</th>
<th style="text-align: right;">2.5 %</th>
<th style="text-align: right;">97.5 %</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">pared1</td>
<td style="text-align: right;">1.0476901</td>
<td style="text-align: right;">0.5281768</td>
<td style="text-align: right;">1.5721750</td>
</tr>
<tr class="even">
<td style="text-align: left;">public1</td>
<td style="text-align: right;">-0.0587857</td>
<td style="text-align: right;">-0.6522060</td>
<td style="text-align: right;">0.5191384</td>
</tr>
<tr class="odd">
<td style="text-align: left;">gpa</td>
<td style="text-align: right;">0.6159406</td>
<td style="text-align: right;">0.1076202</td>
<td style="text-align: right;">1.1309148</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>When interpreting the confidence interval of the logit values, if 0 is included in the interval, it implies that the effect of the predictor variables on the outcome is not statistically significant. The true log odds could be negative, positive, or effectively zero, suggesting no effect.</p>
<p>Table 3 shows the logit estimates and their corresponding <span class="math inline">\(95\%\)</span> confidence intervals for three predictors in a logistic regression model: <code>pared1</code>, <code>public1</code>, and <code>gpa</code>. The logit estimate for <code>pared1</code> is <span class="math inline">\(1.0477\)</span> indicating a positive effect on the oucome, with a confidence interval not including zero implying it is statistically significant. Conversely, <code>public1</code> has a logit estimate of <span class="math inline">\(-0.0588\)</span> with a confidence interval that includes zero, suggesting that this predictor does not have a statistically significant impact on the outcome. Finally, <code>gpa</code> shows a positive logit of <span class="math inline">\(0.6159\)</span> with a confidence interval from <span class="math inline">\(0.1076\)</span> to <span class="math inline">\(1.1309\)</span>, also indicating a significant positive effect on the outcome, as the interval does not include zero.</p>
<p>For easier comprehension, it is recommended to convert the log of odds into odds ratio. This can be done by taking the exponential to the log odds value. While at it, the <span class="math inline">\(95\%\)</span> confidence interval is calculated for each coefficient.</p>
<!-- If the 95% CI does not cross 0, the parameter estimate is statistically significant. So, for the -->
<!-- odds ratio CI, if 1 is in the interval, it suggests there is no significant different in 1. -->
<p>If the confidence interval for the odds ratio includes the number 1 then the calculated odds ratio would not be considered statistically significant. This can be seen from the interpretation of the odds ratio. An odds ratio of less than 1 indicates that the odds of the outcome occurring are lower with the presence or increase of the predictor variable. Conversely, an odds ratio greater than 1 suggests that the odds of the outcome occurring are higher with the presence or increase of the predictor variable. An odds ratio of exactly 1 implies that the predictor variable has no effect on the odds of the outcome; in other words, the odds are the same regardless of the presence or level of the predictor variable. Therefore, when the confidence interval for an odds ratio includes the 1, it indicates uncertainty about whether the predictor variable positively or negatively affects the odds of the outcome occurring. This means the true population odds ratio might be greater than, less than, or exactly 1 (Tenny and Hoffman, 2023).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">exp</span>(<span class="fu">cbind</span>(<span class="at">OR =</span> <span class="fu">coef</span>(fit), ci)),</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">caption =</span> <span class="st">"Condidence Interval of Odds Ratio"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Condidence Interval of Odds Ratio</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">OR</th>
<th style="text-align: right;">2.5 %</th>
<th style="text-align: right;">97.5 %</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">pared1</td>
<td style="text-align: right;">2.8510579</td>
<td style="text-align: right;">1.6958376</td>
<td style="text-align: right;">4.817114</td>
</tr>
<tr class="even">
<td style="text-align: left;">public1</td>
<td style="text-align: right;">0.9429088</td>
<td style="text-align: right;">0.5208954</td>
<td style="text-align: right;">1.680579</td>
</tr>
<tr class="odd">
<td style="text-align: left;">gpa</td>
<td style="text-align: right;">1.8513972</td>
<td style="text-align: right;">1.1136247</td>
<td style="text-align: right;">3.098490</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>pared1</strong>: For students whose parents did attend college, the odds of being more likely (i.e., very or somewhat likely versus unlikely) to apply is 2.85 times—185% increase— that of students whose parents did not go to college, holding constant all other variables.</p>
<p><strong>public</strong>: There is no statistically significant difference in the odds of a student being in a higher category of likelihood to apply to graduate school between public and private undergraduate institutions. The odds ratio of 0.94 suggests that the odds are slightly lower for students from public institutions, but the 95% CI includes 1, indicating that the difference is not statistically significant.</p>
<p><strong>gpa</strong>: For every one unit increase in student’s GPA the odds of being more likely to apply (very or somewhat likely versus unlikely) is multiplied 1.85 times (i.e., increases 85%), holding constant all other variables.</p>
<p>Having established the parameters of our regression models, we now proceed to assess their fit and robustness. This next section evaluates how well the models conform to the observed data, using a variety of diagnostic statistics and tests to ensure the reliability and validity of our findings.</p>
</section>
<section id="assessment-of-model-fit" class="level3">
<h3 class="anchored" data-anchor-id="assessment-of-model-fit">Assessment of Model Fit</h3>
<p>This section contains a discussion on assessing the model using the different metrics discussed in the model evaluation and diagnostic section. The first metric to perform is the pseudo R-squared. To do it, we must remodel again the ordinal logistic regression using the <code>clm()</code> function as the respective functions of the other metrics do not work in <code>polr()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">clm</span>(apply <span class="sc">~</span> pared <span class="sc">+</span> public <span class="sc">+</span> gpa, <span class="at">data =</span> training_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Pseudo R-Squared</strong></p>
<p>There are three different pseudo R-squared utilized in this study, McFadden, Cox and Snell, and Nagelkerke’s pseudo R-squared. It is time-consuming to calculate each using different functions luckily, the <code>nagelkerke()</code> function performs the three.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">nagelkerke</span>(model)<span class="sc">$</span>Pseudo.R.squared.for.model.vs.null, </span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">caption =</span> <span class="st">"Pseudo R-Squared"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Pseudo R-Squared</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Pseudo.R.squared</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">McFadden</td>
<td style="text-align: right;">0.0326231</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cox and Snell (ML)</td>
<td style="text-align: right;">0.0586601</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Nagelkerke (Cragg and Uhler)</td>
<td style="text-align: right;">0.0695655</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Table 5 displays three pseudo <span class="math inline">\(R^2\)</span> values for a logistic regression model: McFadden’s at 0.0326, Cox and Snell’s at 0.05867, and Nagelkerke’s at 0.0695. These metrics assess the goodness of fit of the model, with each indicating a relatively low explanatory power: McFadden’s value suggests that the independent variables explain approximately 3.26% of the variance in the dependent variable. Cox and Snell’s and Nagelkerke’s values are slightly higher, indicating slightly better but still modest explanatory power. Nagelkerke’s value, the highest, suggests that the model explains about 6.96% of the variance.</p>
<p><strong>Likelihood Ratio Test</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">nagelkerke</span>(model)<span class="sc">$</span>Likelihood.ratio.test, </span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">caption =</span> <span class="st">"Likelihood Ratio Test"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Likelihood Ratio Test</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Df.diff</th>
<th style="text-align: right;">LogLik.diff</th>
<th style="text-align: right;">Chisq</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: right;">-3</td>
<td style="text-align: right;">-12.09</td>
<td style="text-align: right;">24.18</td>
<td style="text-align: right;">2.29e-05</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Table 6 shows the results of a LRT. The test compares two nested models, with the difference in degrees of freedom (<code>Df.diff</code>) being <span class="math inline">\(-3\)</span>, indicating that the full model has three additional parameters compared to the reduced model. The <code>LogLik.diff</code> of <span class="math inline">\(-12.09\)</span> is the difference in the log-likelihoods between the two models, where the full model has a lower log-likelihood. Despite this, the Chi-square value of 24.18 and the very small p-value suggesting that the addition of these three parameters significantly improves the model fit. Therefore, the null hypothesis is rejected which means that adding the predictors is better than the null model with no predictors.</p>
<p><strong>Lipsitz Test</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lipsitz.test</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Lipsitz goodness of fit test for ordinal response models

data:  formula:  apply ~ pared + public + gpa
LR statistic = 8.5407, df = 9, p-value = 0.4807</code></pre>
</div>
</div>
<p>Since the p-value is greater than <span class="math inline">\(0.05\)</span>, we do not reject the null hypothesis. The model is adequately fitting the ordinal data. The predictions of the model are the same or closely the same as the actual data</p>
<p><strong>Accuracy</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>testing_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"testing_data.csv"</span>)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>testing_data<span class="sc">$</span>apply <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(testing_data<span class="sc">$</span>apply <span class="sc">==</span> <span class="st">"unlikely"</span>, <span class="dv">1</span>, </span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>                      <span class="fu">ifelse</span>(testing_data<span class="sc">$</span>apply <span class="sc">==</span> <span class="st">"somewhat likely"</span>, <span class="dv">2</span>, <span class="dv">3</span>))</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>testing_data<span class="sc">$</span>apply <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(testing_data<span class="sc">$</span>apply)</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>testing_data<span class="sc">$</span>pared <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(testing_data<span class="sc">$</span>pared)</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>testing_data<span class="sc">$</span>public <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(testing_data<span class="sc">$</span>public)</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>predicted_data <span class="ot">&lt;-</span> <span class="fu">predict</span>(fit, testing_data, <span class="at">type =</span> <span class="st">"class"</span>)</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a><span class="fu">confusionMatrix</span>(testing_data<span class="sc">$</span>apply, predicted_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The table presented below is only a portion of the output in the <code>confusionMatrix()</code> function. The full output will be presented in the appendix.</p>
<table class="table">
<caption>Confusion Matrix and Statistics by Class</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th colspan="3" style="text-align: center;">Reference</th>
<th style="text-align: center;">Accuracy</th>
<th colspan="3" style="text-align: center;">Sensitivity</th>
<th colspan="3" style="text-align: center;">Specificity</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Prediction</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">3</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">C1</td>
<td style="text-align: center;">C2</td>
<td style="text-align: center;">C3</td>
<td style="text-align: center;">C1</td>
<td style="text-align: center;">C2</td>
<td style="text-align: center;">C3</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: center;">48</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: center;">28</td>
<td style="text-align: center;">11</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0.59</td>
<td style="text-align: center;">0.58</td>
<td style="text-align: center;">0.65</td>
<td style="text-align: center;">NA</td>
<td style="text-align: center;">0.76</td>
<td style="text-align: center;">0.66</td>
<td style="text-align: center;">0.91</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
<p><strong>Confusion Matrix</strong></p>
<p>The model predicted 48 out of 52 actual Class 1 instances correctly, misclassifying 4 as Class 2 and 0 as Class 3. Out of 39 actual Class 2 instances, 11 were correctly predicted, but 28 were incorrectly classified as Class 1, showing a high misclassification rate for Somewhat likely. There were 9 actual Class 3 instances; 2 were correctly predicted, while 7 were misclassified as Class 1, indicating difficulty in correctly classifying this class.</p>
<p><strong>Accuracy</strong></p>
<p>The overall accuracy of the model is 0.59, indicating that 59% of all predictions made by the model are correct. This suggests moderate predictive power.</p>
<p><strong>Sensitivity</strong></p>
<p>About 58% of actual Class 1 instances were identified correctly, suggesting moderate sensitivity for this class. The model correctly identified about 65% of actual Class 2 instances, showing slightly better sensitivity for this class. Not available (NA), likely due to the small number of Class 3 instances present, making it difficult to compute a reliable sensitivity measure.</p>
<p><strong>Specificity</strong></p>
<p>Approximately 76% of instances not belonging to Class 1 were correctly identified, indicating good specificity. About 66% of non-Class 2 instances were correctly identified, showing moderate specificity. The model was very effective in identifying non-Class 3 instances, with a specificity of 91%, suggesting that while it struggles to identify Class 3 correctly, it rarely misclassifies other classes as Class 3.</p>
<p>Now that the diagnostics for the model are complete, the next step is to remodel the data by removing any non-statistically significant variables. This will help determine if there is an improvement in the model fit. The subsequent section will provide a discussion comparing the differences in coefficients, intercepts, inferences, and model diagnostics.</p>
</section>
<section id="removing-insignificant-variable" class="level3">
<h3 class="anchored" data-anchor-id="removing-insignificant-variable">Removing Insignificant Variable</h3>
<p>This section contains the remodeled version of the first example with the independent variable removed, the <code>public</code> variable since it is not statistically significant. Furthermore, the same flow is performed—modeling, inference, and assessment of model fit. The full output from <code>R</code> is shown in the Appendix. There will be a selection of which model is best by checking and comparing the value of the remodeled version and the original model in terms of the coefficients, intercepts, inference, and metrics utilized in assessing the model. The <code>Residual Deviance</code> and <code>AIC</code> will also be added to the criteria for choosing which of the two models is better.</p>
</section>
<section id="modeling-1" class="level3">
<h3 class="anchored" data-anchor-id="modeling-1">Modeling</h3>
<table class="table">
<caption>Comparison of Coefficients and Intercepts</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th colspan="4" style="text-align: center;">Original</th>
<th style="text-align: left;"></th>
<th colspan="4" style="text-align: center;">Remodeled</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">Value</td>
<td style="text-align: center;">Std. Error</td>
<td style="text-align: center;">t value</td>
<td style="text-align: center;">p value</td>
<td style="text-align: left;"></td>
<td style="text-align: center;">Value</td>
<td style="text-align: center;">Std. Error</td>
<td style="text-align: center;">t value</td>
<td style="text-align: center;">p value</td>
</tr>
<tr class="even">
<td style="text-align: right;">pared1</td>
<td style="text-align: center;">1.0477</td>
<td style="text-align: center;">0.2658</td>
<td style="text-align: center;">3.9418</td>
<td style="text-align: center;">0.0001</td>
<td style="text-align: left;"></td>
<td style="text-align: center;">1.0457</td>
<td style="text-align: center;">0.2658</td>
<td style="text-align: center;">3.9418</td>
<td style="text-align: center;">0.0001</td>
</tr>
<tr class="odd">
<td style="text-align: right;">public1</td>
<td style="text-align: center;">-0.0588</td>
<td style="text-align: center;">0.2979</td>
<td style="text-align: center;">-0.1974</td>
<td style="text-align: center;">0.8435</td>
<td style="text-align: left;"></td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
</tr>
<tr class="even">
<td style="text-align: right;">gpa</td>
<td style="text-align: center;">0.6159</td>
<td style="text-align: center;">0.2606</td>
<td style="text-align: center;">2.3632</td>
<td style="text-align: center;">0.0181</td>
<td style="text-align: left;"></td>
<td style="text-align: center;">0.6042</td>
<td style="text-align: center;">0.2539</td>
<td style="text-align: center;">2.3794</td>
<td style="text-align: center;">0.0173</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1|2</td>
<td style="text-align: center;">2.2039</td>
<td style="text-align: center;">0.7795</td>
<td style="text-align: center;">2.8272</td>
<td style="text-align: center;">0.0047</td>
<td style="text-align: left;"></td>
<td style="text-align: center;">2.1763</td>
<td style="text-align: center;">0.7671</td>
<td style="text-align: center;">2.8370</td>
<td style="text-align: center;">0.0046</td>
</tr>
<tr class="even">
<td style="text-align: right;">2|3</td>
<td style="text-align: center;">4.2994</td>
<td style="text-align: center;">0.8043</td>
<td style="text-align: center;">5.3453</td>
<td style="text-align: center;">0.0000</td>
<td style="text-align: left;"></td>
<td style="text-align: center;">4.2716</td>
<td style="text-align: center;">0.7922</td>
<td style="text-align: center;">5.3924</td>
<td style="text-align: center;">0.0000</td>
</tr>
</tbody>
</table>
<p>Table 8 displays a comparison of coefficients and intercepts between the original and the remodeled(where the non-significant variable <code>public1</code> was removed). In the remodeled version, there is a slight decrease in the coefficients for <code>pared1</code> and <code>gpa</code>, but both maintaining statistical significance with minor adjustments in their standard errors and p-values. The intercepts for the ordinal thresholds <code>1|2</code> and <code>2|3</code> also slightly decrease but continue to show significances. The removal of <code>public1</code> seems to be improving the model fit.</p>
<p><strong>Confidence Interval</strong></p>
<table class="table">
<caption>Comparison of Confidence Interval of Log Odds</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th colspan="3" style="text-align: center;">Original</th>
<th style="text-align: left;"></th>
<th colspan="3" style="text-align: center;">Remodeled</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">logit</td>
<td style="text-align: center;">2.5 %</td>
<td style="text-align: center;">97.5 %</td>
<td style="text-align: left;"></td>
<td style="text-align: center;">logit</td>
<td style="text-align: center;">2.5 %</td>
<td style="text-align: center;">97.5 %</td>
</tr>
<tr class="even">
<td style="text-align: right;">pared1</td>
<td style="text-align: center;">1.0477</td>
<td style="text-align: center;">0.5282</td>
<td style="text-align: center;">1.5722</td>
<td style="text-align: left;"></td>
<td style="text-align: center;">1.0457</td>
<td style="text-align: center;">0.5265</td>
<td style="text-align: center;">1.570</td>
</tr>
<tr class="odd">
<td style="text-align: right;">public1</td>
<td style="text-align: center;">-0.0588</td>
<td style="text-align: center;">-0.6522</td>
<td style="text-align: center;">0.5191</td>
<td style="text-align: left;"></td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
</tr>
<tr class="even">
<td style="text-align: right;">gpa</td>
<td style="text-align: center;">0.6159</td>
<td style="text-align: center;">0.1076</td>
<td style="text-align: center;">1.1309</td>
<td style="text-align: left;"></td>
<td style="text-align: center;">0.6042</td>
<td style="text-align: center;">0.1090</td>
<td style="text-align: center;">1.106</td>
</tr>
</tbody>
</table>
<p>The log odds of <code>pared1</code> remain almost unchanged. The same can be said for its confidence interval. The coefficient for <code>gpa</code> also shows a slight adjustment. The comparison of the two models, albeit with slight changes in the values, is maintaining its significant impact.</p>
<table class="table">
<caption>Comparison of Confidence Interval of Odds Ratio</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th colspan="3" style="text-align: center;">Original</th>
<th style="text-align: left;"></th>
<th colspan="3" style="text-align: center;">Remodeled</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">OR</td>
<td style="text-align: center;">2.5 %</td>
<td style="text-align: center;">97.5 %</td>
<td style="text-align: left;"></td>
<td style="text-align: center;">OR</td>
<td style="text-align: center;">2.5 %</td>
<td style="text-align: center;">97.5 %</td>
</tr>
<tr class="even">
<td style="text-align: right;">pared1</td>
<td style="text-align: center;">2.8511</td>
<td style="text-align: center;">1.6958</td>
<td style="text-align: center;">4.8170</td>
<td style="text-align: left;"></td>
<td style="text-align: center;">2.8454</td>
<td style="text-align: center;">1.6931</td>
<td style="text-align: center;">4.8065</td>
</tr>
<tr class="odd">
<td style="text-align: right;">public1</td>
<td style="text-align: center;">0.9429</td>
<td style="text-align: center;">0.5209</td>
<td style="text-align: center;">1.6806</td>
<td style="text-align: left;"></td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
</tr>
<tr class="even">
<td style="text-align: right;">gpa</td>
<td style="text-align: center;">1.8514</td>
<td style="text-align: center;">1.1136</td>
<td style="text-align: center;">3.098</td>
<td style="text-align: left;"></td>
<td style="text-align: center;">1.8299</td>
<td style="text-align: center;">1.1152</td>
<td style="text-align: center;">3.0223</td>
</tr>
</tbody>
</table>
<p>The comparison of the odds ratio and confidence interval shows a slight change in the values between the two models. The two models maintained a significant impact.</p>
<p><strong>Pseudo R-Squared</strong></p>
<table class="table">
<caption>Comparison of Pseudo R-Squared</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th colspan="3" style="text-align: center;">Pseudo R-Squared</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">Original</td>
<td style="text-align: left;"></td>
<td style="text-align: center;">Remodeled</td>
</tr>
<tr class="even">
<td style="text-align: left;">McFadden</td>
<td style="text-align: center;">0.0326231</td>
<td style="text-align: left;"></td>
<td style="text-align: center;">0.0325706</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cox and Snell (ML)</td>
<td style="text-align: center;">0.0586601</td>
<td style="text-align: left;"></td>
<td style="text-align: center;">0.0585685</td>
</tr>
<tr class="even">
<td style="text-align: left;">Nagelkerke (Cragg and Uhler)</td>
<td style="text-align: center;">0.0695655</td>
<td style="text-align: left;"></td>
<td style="text-align: center;">0.0694569</td>
</tr>
</tbody>
</table>
<p>Comparing the <code>Pseudo R-squared</code> between the two models, there are changes in the three versions of <span class="math inline">\(R^2\)</span>. These changes can be observed in the 4th decimal place, with the remodeled logistic regression slightly decreasing its values. This is the case because the <code>public</code> variable has an association with the dependent variable, hence, when it is removed in the remodeled version, the values of <span class="math inline">\(R^2\)</span> decreased.</p>
<p><strong>Likelihood Ratio Test</strong></p>
<table class="table">
<caption>Comparison of Likelihood Ratio Test</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Df.diff</th>
<th style="text-align: left;">LogLik.diff</th>
<th style="text-align: left;">Chisq</th>
<th style="text-align: left;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Original</td>
<td style="text-align: left;">-3</td>
<td style="text-align: left;">-12.09</td>
<td style="text-align: left;">24.18</td>
<td style="text-align: left;">2.29e-05</td>
</tr>
<tr class="even">
<td style="text-align: left;">Remodeled</td>
<td style="text-align: left;">-2</td>
<td style="text-align: left;">-12.071</td>
<td style="text-align: left;">24.141</td>
<td style="text-align: left;">5.7e-06</td>
</tr>
</tbody>
</table>
<p>Of the two LRTs, the null hypothesis is rejected, suggesting that adding the predictors is better than the null model with no predictors.</p>
<p><strong>Lipsitz Test</strong></p>
<table class="table">
<caption>Comparison of Lipsitz Goodness of Fit Test</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">LR statistic</th>
<th style="text-align: left;">df</th>
<th style="text-align: left;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Original</td>
<td style="text-align: left;">8.5407</td>
<td style="text-align: left;">9</td>
<td style="text-align: left;">0.4807</td>
</tr>
<tr class="even">
<td style="text-align: left;">Remodeled</td>
<td style="text-align: left;">8.5904</td>
<td style="text-align: left;">9</td>
<td style="text-align: left;">0.4759</td>
</tr>
</tbody>
</table>
<p>The two models are adequately fitting the ordinal data. The predictions of the model are the same or closely the same as the actual data.</p>
<p><strong>Accuracy</strong></p>
<table class="table">
<caption>Comparison of Confusion Matrix</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;"></th>
<th colspan="3" style="text-align: center;">Reference</th>
<th style="text-align: center;">Accuracy</th>
<th colspan="3" style="text-align: center;">Sensitivity</th>
<th colspan="3" style="text-align: center;">Specificity</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">Prediction</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">3</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">C1</td>
<td style="text-align: center;">C2</td>
<td style="text-align: center;">C3</td>
<td style="text-align: center;">C1</td>
<td style="text-align: center;">C2</td>
<td style="text-align: center;">C3</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;">1</td>
<td style="text-align: center;">48</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Original</td>
<td style="text-align: right;">2</td>
<td style="text-align: center;">28</td>
<td style="text-align: center;">11</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0.59</td>
<td style="text-align: center;">0.58</td>
<td style="text-align: center;">0.65</td>
<td style="text-align: center;">NA</td>
<td style="text-align: center;">0.76</td>
<td style="text-align: center;">0.66</td>
<td style="text-align: center;">0.91</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;">3</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: right;">1</td>
<td style="text-align: center;">48</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Remodeled</td>
<td style="text-align: right;">2</td>
<td style="text-align: center;">28</td>
<td style="text-align: center;">11</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0.59</td>
<td style="text-align: center;">0.58</td>
<td style="text-align: center;">0.65</td>
<td style="text-align: center;">NA</td>
<td style="text-align: center;">0.76</td>
<td style="text-align: center;">0.66</td>
<td style="text-align: center;">0.91</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: right;">3</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
<p>There are no changes in the comparison of the two models in the table above. The two models show the same values in accuracy, sensitivity, and specificity. The next table will show the <code>AIC</code> and <code>Residual Deviance</code> values, where the lower values correspond to the better model.</p>
<table class="table">
<caption>Comparison of Residual Deviance and AIC</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Residual Deviance</th>
<th style="text-align: left;">AIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Original</td>
<td style="text-align: left;">717.0249</td>
<td style="text-align: left;">727.0249</td>
</tr>
<tr class="even">
<td style="text-align: left;">Remodeled</td>
<td style="text-align: left;">717.0638</td>
<td style="text-align: left;">725.0638</td>
</tr>
</tbody>
</table>
<p>The Table 15 presents a comparison of the Residual Deviance and Akaike Information Criterion (AIC) between the original and remodeled ordinal logistic regression. The Residual Deviance, which measures the unexplained variance by the model, shows a slight increase with 0.0389, which suggests a nearly identical fit with respect of explaining the variability in the data. However, the AIC, is slightly lower in the remodeled model compared to the original. This reduction indicates that the remodeled model, despite a trivial increase in Residual Deviance, is considered more efficient due to either the parsimony of the model or the trade-off between the model complexity and fit. However, this is not true for all cases, it may because of a chance. To assess if there is significant difference in the AIC of original and remodeled and the Residual deviance, performing bootstrap analysis provides a robust method to estimate the distribution of these differences under the assumption that the sampled data adequately represent the population.</p>
<p><strong>Bootstrapping</strong></p>
<p>The bootstrap process involves resampling the original dataset 1000 times and for each sample. In calculating the difference between AIC and Residual Deviance, the statistic of the original is subtracted from the remodeled. The code of bootstrapping can be seen in the Appendix.</p>
<table class="table">
<caption>Bootstrap Statistics</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">original</th>
<th style="text-align: center;">bias</th>
<th style="text-align: center;">std. error</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">t1*</td>
<td style="text-align: left;">1.96108366</td>
<td style="text-align: left;">-1.243752</td>
<td style="text-align: left;">1.737844</td>
</tr>
<tr class="even">
<td style="text-align: left;">t2*</td>
<td style="text-align: left;">-0.03891634</td>
<td style="text-align: left;">-1.243752</td>
<td style="text-align: left;">1.737844</td>
</tr>
</tbody>
</table>
<p>The table above is the bootstrap analysis performed in <code>R</code>, where the <span class="math inline">\(t1*\)</span> represents he difference in AIC, the <span class="math inline">\(t2*\)</span> is for the difference in Residual Deviance.</p>
<p><span class="math inline">\(t1*\)</span></p>
<p>The original difference in AIC between the original and remodeled suggests that the remodeled might have a slightly lower AIC. The negative bias suggests that the bootstrap samples yielded a smaller difference than this original estimate, implies that the AIC of the remodeled model was not as consistently lower. The standard error is relatively high and that indicates that there is variability in the AIC differences across the bootstrap samples.</p>
<p><span class="math inline">\(t2*\)</span></p>
<p>The original difference in residual deviance is nearly zero, hence, this suggests that there is no significant difference in the goodness of fit between the two models based on the original sample. The similar negative bias here as well indicates that the bootstrap samples often show no consistent advantage for either model in terms of fitting the data better. There is no clear difference in model fit between the original and remodeled.</p>
<table class="table">
<caption>Bootstrap Confidence Interval</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Level</th>
<th style="text-align: center;">Basic</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(t1*\)</span></td>
<td style="text-align: left;">95 %</td>
<td style="text-align: center;">(1.923, 8.295)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(t2*\)</span></td>
<td style="text-align: left;">95 %</td>
<td style="text-align: center;">(-0.0766, 6.2952)</td>
</tr>
</tbody>
</table>
<p>The Basic CI method is non-parametric and does not assume any specific distribution of the bootstrap estimates. For <span class="math inline">\(t1*\)</span>, the interval suggests a significant difference where the original model likely has a higher AIC than the remodeled model. For the <span class="math inline">\(t2*\)</span>, there is no clear evidence of significant difference in Residual Deviance between the two models since there is zero in the interval.</p>
</section>
<section id="example-2" class="level3">
<h3 class="anchored" data-anchor-id="example-2">Example 2</h3>
<p>The Titanic sank on April 15, 1912, during her maiden voyage after colliding with an iceberg. The data can be found on the <code>carData</code> package, <code>TitanicSurviaval</code>, which contains information on the survival status, sex, age, and passenger class of 1309 passengers.<br>
</p>
<p><strong>Feature description</strong></p>
<ul>
<li><p><strong>survived</strong> - 1 if yes, 0 if did not survived;</p></li>
<li><p><strong>sex</strong> - 1 if male, 0 for female;</p></li>
<li><p><strong>age</strong> - in years (and for some children, fractions of a year); and</p></li>
<li><p><strong>passengerClass</strong>(Dependent Variable) - class of the passengers, either 1st, 2nd, or 3rd class.</p></li>
</ul>
<p><strong>Goal</strong></p>
<p>To perform ordinal logistic regression with passenger class as the dependent variable and survival status, sex, and age as independent variables and understand how these factors influenced the socioeconomic status of passengers aboard the Titanic. Specifically, the study aims to statistically quantify the extent to which survival outcomes, gender differences, and age disparities may have been associated with the class of the passengers.<br>
</p>
<p><strong>Loading the Dataset</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>data2 <span class="ot">&lt;-</span> TitanicSurvival</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">head</span>(data2),</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">caption =</span> <span class="st">"First Six Rows of the Titanic Survival Data"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>First Six Rows of the Titanic Survival Data</caption>
<colgroup>
<col style="width: 45%">
<col style="width: 12%">
<col style="width: 9%">
<col style="width: 11%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">survived</th>
<th style="text-align: left;">sex</th>
<th style="text-align: right;">age</th>
<th style="text-align: left;">passengerClass</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Allen, Miss. Elisabeth Walton</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">female</td>
<td style="text-align: right;">29.0000</td>
<td style="text-align: left;">1st</td>
</tr>
<tr class="even">
<td style="text-align: left;">Allison, Master. Hudson Trevor</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">male</td>
<td style="text-align: right;">0.9167</td>
<td style="text-align: left;">1st</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Allison, Miss. Helen Loraine</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">female</td>
<td style="text-align: right;">2.0000</td>
<td style="text-align: left;">1st</td>
</tr>
<tr class="even">
<td style="text-align: left;">Allison, Mr.&nbsp;Hudson Joshua Crei</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">male</td>
<td style="text-align: right;">30.0000</td>
<td style="text-align: left;">1st</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Allison, Mrs.&nbsp;Hudson J C (Bessi</td>
<td style="text-align: left;">no</td>
<td style="text-align: left;">female</td>
<td style="text-align: right;">25.0000</td>
<td style="text-align: left;">1st</td>
</tr>
<tr class="even">
<td style="text-align: left;">Anderson, Mr.&nbsp;Harry</td>
<td style="text-align: left;">yes</td>
<td style="text-align: left;">male</td>
<td style="text-align: right;">48.0000</td>
<td style="text-align: left;">1st</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="exploratory-data-analysis" class="level3">
<h3 class="anchored" data-anchor-id="exploratory-data-analysis">Exploratory Data Analysis</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(data2, <span class="cf">function</span>(x) <span class="fu">sum</span>(<span class="fu">is.na</span>(x)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      survived            sex            age passengerClass 
             0              0            263              0 </code></pre>
</div>
</div>
<p>The output of the code above contains 263 in the <code>age</code> which suggests that there are 263 passengers with their age not written in the data. Imputation can fill these missing values in the data, but this paper will only be limited to removing the missing values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>data2 <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(data2)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(data2, <span class="cf">function</span>(x) <span class="fu">sum</span>(<span class="fu">is.na</span>(x)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      survived            sex            age passengerClass 
             0              0              0              0 </code></pre>
</div>
</div>
<p><strong>Descriptive Statistics</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(data2[, <span class="fu">c</span>(<span class="st">"survived"</span>, <span class="st">"sex"</span>, <span class="st">"passengerClass"</span>)], table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$survived

 no yes 
619 427 

$sex

female   male 
   388    658 

$passengerClass

1st 2nd 3rd 
284 261 501 </code></pre>
</div>
</div>
<p>The output shown provides the frequency of each of the categorical variable. Of the total passengers, 619 did not survive while 427 survived, highlighting the tragedy’s high fatality rate. Regarding gender distribution, there were significantly more males (658) than females (388) on board. In terms of passenger class, a majority were in third class (501), followed by first (284) and second class (261), reflecting the socio-economic diversity of the passengers.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ftable</span>(<span class="fu">xtabs</span>(<span class="sc">~</span> survived <span class="sc">+</span> passengerClass <span class="sc">+</span> sex, <span class="at">data =</span> data2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                        sex female male
survived passengerClass                
no       1st                     5   98
         2nd                    11  135
         3rd                    80  290
yes      1st                   128   53
         2nd                    92   23
         3rd                    72   59</code></pre>
</div>
</div>
<p>The contingency table illustrates the distribution of Titanic passengers across survival status, passenger class, and sex. For the passengers who did not survived, majority of it were of the males in 3rd class around 290 out of 370 male non-survivors. In contrast, females in 1st class had the highest survival rates, with 128 out of 133 female 1st class passengers surviving. It is worth noticing that are cell with low frequency in different class.</p>

<!-- This table illustrates the stark differences in survival rates between sexes and classes, with first-class passengers, particularly women, having much higher survival rates compared to third-class passengers, especially men. This suggests that socio-economic status and gender played critical roles in survival during the Titanic disaster, highlighting disparities in safety and evacuation priorities. -->
<p>The class of the categorical variables of the dataset is changed into factor as this will be necessary for the modeling part.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>data2<span class="sc">$</span>passengerClass <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(data2<span class="sc">$</span>passengerClass)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>data2<span class="sc">$</span>survived <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(data2<span class="sc">$</span>survived)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>data2<span class="sc">$</span>sex <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(data2<span class="sc">$</span>sex)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The boxplot is performed to investigate the presence of outliers in the dataset.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="ordered_logit_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" style="width:70.0%"></p>
<figcaption class="figure-caption">Boxplot of survived variable</figcaption>
</figure>
</div>
</div>
</div>
<p>Figure 3 presents boxplots depicting the age distribution of Titanic passengers across different classes (1st, 2nd, 3rd), split by their survival status (yes, no). In both survival categories, first-class passengers tend to be older compared to those in second and third classes. The age ranges in first class also appear wider, particularly among survivors. Second and third class passengers show younger median ages, with tighter interquartile ranges, especially noticeable in third class. Across all classes, survivors tend to have slightly higher median ages than those who did not survive, suggesting that age may have played a role in survival, particularly in lower classes. The presence of outliers across all groups indicates variability in age among passengers within each class and survival category.</p>
<p><strong>Partitioning</strong></p>
<p>A partition of <span class="math inline">\(80\%\)</span> of the data will be in the training data, and the remaining <span class="math inline">\(20\%\)</span> is the testing data. The code below performs a stratified partitioning in the titanic dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2024</span>)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>split <span class="ot">&lt;-</span> <span class="fu">initial_split</span>(data2, <span class="at">prop =</span> <span class="fl">0.80</span>, <span class="at">strata =</span> <span class="st">"passengerClass"</span>)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create training and testing sets using the index</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>training_data <span class="ot">&lt;-</span> <span class="fu">training</span>(split)</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>testing_data <span class="ot">&lt;-</span> <span class="fu">testing</span>(split)</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste0</span>(<span class="st">"Training Data: "</span>, <span class="fu">nrow</span>(training_data),</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>             <span class="st">"; Testing Data: "</span>, <span class="fu">nrow</span>(testing_data)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Training Data: 835; Testing Data: 211"</code></pre>
</div>
</div>
</section>
<section id="checking-assumptions-1" class="level3">
<h3 class="anchored" data-anchor-id="checking-assumptions-1">Checking Assumptions</h3>
<p>The descriptive statistics performed earlier shows evidence that the dependent variable is ordinal in nature. No zero count was also found in each of the categories of the dependent variable.</p>
<p><strong>Checking the Presence of Multicollinearity</strong></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggpairs</span>(training_data[, <span class="sc">-</span><span class="dv">4</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="ordered_logit_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid figure-img" style="width:70.0%"></p>
<figcaption class="figure-caption">Correlation Assumption</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Checking Parallel Regression Lines</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>par.reg <span class="ot">&lt;-</span> <span class="fu">polr</span>(passengerClass <span class="sc">~</span> survived <span class="sc">+</span> sex <span class="sc">+</span> age, <span class="at">data =</span> training_data)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Brant's Test</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="fu">brant</span>(par.reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>-------------------------------------------- 
Test for    X2  df  probability 
-------------------------------------------- 
Omnibus     2.89    3   0.41
survivedyes 1.79    1   0.18
sexmale     0.57    1   0.45
age     1.79    1   0.18
-------------------------------------------- 

H0: Parallel Regression Assumption holds</code></pre>
</div>
</div>
<p>The overall test and the results for individual predictors indicate that all variables satisfy the assumption since the p-value is greater than <span class="math inline">\(0.05\)</span>.</p>
<p>Now the checking of assumptions is done and none are violated, next thing to perform is to proceed in the modeling part of the ordinal logistic regression.</p>
</section>
<section id="modeling-2" class="level3">
<h3 class="anchored" data-anchor-id="modeling-2">Modeling</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">polr</span>(passengerClass <span class="sc">~</span> survived <span class="sc">+</span> sex <span class="sc">+</span> age, <span class="at">data =</span> training_data, <span class="at">Hess=</span><span class="cn">TRUE</span>)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
polr(formula = passengerClass ~ survived + sex + age, data = training_data, 
    Hess = TRUE)

Coefficients:
               Value Std. Error t value
survivedyes -1.75059   0.183540  -9.538
sexmale     -0.27452   0.180928  -1.517
age         -0.06574   0.005419 -12.131

Intercepts:
        Value    Std. Error t value 
1st|2nd  -4.0817   0.2763   -14.7740
2nd|3rd  -2.6878   0.2532   -10.6166

Residual Deviance: 1495.276 
AIC: 1505.276 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>coefs <span class="ot">&lt;-</span> <span class="fu">coef</span>(<span class="fu">summary</span>(fit))</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate P-value</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">pnorm</span>(<span class="fu">abs</span>(coefs[, <span class="st">"t value"</span>]), <span class="at">lower.tail =</span> <span class="cn">FALSE</span>) <span class="sc">*</span> <span class="dv">2</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Add Column</span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>coefs <span class="ot">&lt;-</span> <span class="fu">cbind</span>(coefs, <span class="st">"p value"</span> <span class="ot">=</span> p) </span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">round</span>(coefs, <span class="dv">4</span>), </span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>             <span class="at">caption =</span> <span class="st">"Coefficient and Intercepts of Titanic Survival Data"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Coefficient and Intercepts of Titanic Survival Data</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Value</th>
<th style="text-align: right;">Std. Error</th>
<th style="text-align: right;">t value</th>
<th style="text-align: right;">p value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">survivedyes</td>
<td style="text-align: right;">-1.7506</td>
<td style="text-align: right;">0.1835</td>
<td style="text-align: right;">-9.5379</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="even">
<td style="text-align: left;">sexmale</td>
<td style="text-align: right;">-0.2745</td>
<td style="text-align: right;">0.1809</td>
<td style="text-align: right;">-1.5173</td>
<td style="text-align: right;">0.1292</td>
</tr>
<tr class="odd">
<td style="text-align: left;">age</td>
<td style="text-align: right;">-0.0657</td>
<td style="text-align: right;">0.0054</td>
<td style="text-align: right;">-12.1308</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="even">
<td style="text-align: left;">1st|2nd</td>
<td style="text-align: right;">-4.0817</td>
<td style="text-align: right;">0.2763</td>
<td style="text-align: right;">-14.7740</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2nd|3rd</td>
<td style="text-align: right;">-2.6878</td>
<td style="text-align: right;">0.2532</td>
<td style="text-align: right;">-10.6166</td>
<td style="text-align: right;">0.0000</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The estimated model can be written as: <span class="math display">\[logit(\hat{P}(Y \leq 1) = -4.0817 - (-1.7506)*\textbf{survivedyes} - (-0.2745)*\textbf{sexmale} - ( -0.0657)*\textbf{age}\]</span> <span class="math display">\[logit(\hat{P}(Y \leq 2) = -2.6878 - (-1.7506)*\textbf{survivedyes} - (-0.2745)*\textbf{sexmale} - ( -0.0657)*\textbf{age}\]</span></p>
<p><strong>Interpretation</strong></p>
<p>Coefficients:</p>
<p><strong>survivedyes</strong>: For passenger who survived, the log odds of being in a lower passenger class decrease by approximately 1.7506 units while holding the other variables constant. This implies that among the survivors, there’s a significant decrease in the log odds of being in a lower passenger class than that off being in a higher passenger class. Historical analyses indicate that survival rates on the Titanic were markedly higher for first-class passengers compared to those in lower classes, often attributed to closer proximity to lifeboats and prioritization in lifeboat boarding protocols (Frey, et al.&nbsp;2010).</p>
<p><strong>sexmale</strong>: For male passengers, the log odds of being in a lower passenger class decrease by approximately 0.2745 units compared to the log odds of being in a higher passenger class when other variables are held constant. This suggests that among male passengers, there’s a decrease in the log odds of being in a lower passenger class relative to being in a higher passenger class. This finding contradicts with the historical accounts that Hall (2014) documented. He noted that a significant survival advantage for women during the Titanic disaster attributed to the ‘women and children first’ policy. The lack of significance in this model could be attributed to the specific data or the influence of other variables within the model.</p>
<p><strong>age</strong>: For every one unit increase in age, the log odds of being in a lower passenger class decrease by approximately 0.0657 units when rendering the other variables as constant. The older the passenger are the less likely they are in lower passenger class. According to Spigner (2012) that age played a significant role in survival probabilities on the Titanic, with children and younger women more likely to survive, reflecting societal norms and rescue priorities.</p>
<p>Intercepts:</p>
<p><strong>1st|2nd</strong>: The intercept value for the transition from 1st to 2nd class is -4.0817 when the other variables are zero. In other words, passengers are much less likely to be in the 1st class compared to the 2nd class. By Archibald and Sloan (2011), the substantial social and economic differences between the first and second classes on the Titanic are well-documented, with first-class passengers enjoying considerably more luxury and privileges, which could translate into a higher likelihood of being in a higher class.</p>
<p><strong>2nd|3rd</strong>: The intercept value for the transition from 2nd to 3rd class is -2.6878 when the other variables are held constant. In other words, passengers are much less likely to be in the 2nd class compared to the 3rd class. The differences between second and third classes were significant, with third-class passengers often experiencing much poorer living conditions and having less access to safety measures during the disaster (Beesley, 2011).</p>
<p><strong>Confidence Interval</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>ci <span class="ot">&lt;-</span> <span class="fu">confint</span>(fit, <span class="at">level =</span> <span class="fl">0.95</span>)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">cbind</span>(<span class="at">logit =</span> <span class="fu">coef</span>(fit), ci), </span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">caption =</span> <span class="st">"Condidence Interval of Logit of Titanic Survival Data"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Condidence Interval of Logit of Titanic Survival Data</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">logit</th>
<th style="text-align: right;">2.5 %</th>
<th style="text-align: right;">97.5 %</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">survivedyes</td>
<td style="text-align: right;">-1.750590</td>
<td style="text-align: right;">-2.1154980</td>
<td style="text-align: right;">-1.3953066</td>
</tr>
<tr class="even">
<td style="text-align: left;">sexmale</td>
<td style="text-align: right;">-0.274523</td>
<td style="text-align: right;">-0.6328328</td>
<td style="text-align: right;">0.0771671</td>
</tr>
<tr class="odd">
<td style="text-align: left;">age</td>
<td style="text-align: right;">-0.065737</td>
<td style="text-align: right;">-0.0765378</td>
<td style="text-align: right;">-0.0552818</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Table 20 displays the confidence intervals of the logit coefficients for three independent variables. For ‘survivedyes,’ the logit coefficient is -1.750590, and the confidence interval spans from -2.1154980 to -1.3953066. This interval does not include zero, indicating a statistically significant negative relationship between survival and passenger class. For ‘sexmale,’ the coefficient is -0.274523 with a confidence interval ranging from -0.6328328 to 0.0771671. This interval crosses zero, suggesting that the effect of being male on passenger class may not be statistically significant. Lastly, for ‘age’ the coefficient is -0.065737 with a confidence interval from -0.0765378 to -0.0552818, which also does not include zero, indicating a significant negative effect where older passengers are less likely to be in higher classes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">exp</span>(<span class="fu">cbind</span>(<span class="at">OR =</span> <span class="fu">coef</span>(fit), ci)), </span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">caption =</span> <span class="st">"Condidence Interval of Odds Ratio of Titanic Survival Data"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Condidence Interval of Odds Ratio of Titanic Survival Data</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">OR</th>
<th style="text-align: right;">2.5 %</th>
<th style="text-align: right;">97.5 %</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">survivedyes</td>
<td style="text-align: right;">0.1736715</td>
<td style="text-align: right;">0.1205732</td>
<td style="text-align: right;">0.2477571</td>
</tr>
<tr class="even">
<td style="text-align: left;">sexmale</td>
<td style="text-align: right;">0.7599345</td>
<td style="text-align: right;">0.5310852</td>
<td style="text-align: right;">1.0802226</td>
</tr>
<tr class="odd">
<td style="text-align: left;">age</td>
<td style="text-align: right;">0.9363771</td>
<td style="text-align: right;">0.9263179</td>
<td style="text-align: right;">0.9462185</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>survivedyes</strong>: The odds ratio of 0.1737 indicates that passengers who survived are significantly less likely to belong to a higher passenger class. Specifically, survivors are approximately 82.63% less likely to be in a higher class than those who did not survive, as the odds ratio is less than 1. The 95% confidence interval ranging from 0.12057 to 0.2478 reinforces the statistical significance of this finding, confirming that this is a robust effect.</p>
<p><strong>sexmale</strong>: The odds ratio for males is 0.7599, suggesting that males are less likely to be in a higher passenger class compared to females. However, the confidence interval for this estimate ranges from 0.5311 to 1.0802, which includes 1, indicating that this result is not statistically significant. Thus, sex may not be a strong predictor of passenger class on the Titanic.</p>
<p><strong>age</strong>: The odds ratio for age is 0.9364, implying that for every additional year of age, the likelihood of being in a higher passenger class decreases by about 6.36%. This effect is statistically significant, as the confidence interval (0.9263 to 0.9462) does not include 1. This suggests a consistent trend where older passengers were less likely to be in higher classes.</p>
</section>
<section id="assessing-of-model-fit" class="level3">
<h3 class="anchored" data-anchor-id="assessing-of-model-fit">Assessing of Model Fit</h3>
<p>This section provides a discussion on assessing the model using the same metrics utilized in the first example.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">clm</span>(passengerClass <span class="sc">~</span> survived <span class="sc">+</span> sex <span class="sc">+</span> age, <span class="at">data =</span> training_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Pseudo R-squared</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">nagelkerke</span>(model)<span class="sc">$</span>Pseudo.R.squared.for.model.vs.null, </span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">caption =</span> <span class="st">"Pseudo R-Squared"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Pseudo R-Squared</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Pseudo.R.squared</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">McFadden</td>
<td style="text-align: right;">0.149588</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cox and Snell (ML)</td>
<td style="text-align: right;">0.270207</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Nagelkerke (Cragg and Uhler)</td>
<td style="text-align: right;">0.307667</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The table above shows the same three versions of different <span class="math inline">\(R^2\)</span>. McFadden’s R-squared at 0.149588 suggests a modest explanatory power. Cox and Snell’s and Nagelkerke’s values, at 0.270207 and 0.307667 respectively, provide higher estimates, suggesting a better model fit.</p>
<p><strong>Likelihood Ratio Test</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">nagelkerke</span>(model)<span class="sc">$</span>Likelihood.ratio.test,</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">caption =</span> <span class="st">"Likelihood Ratio Test"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Likelihood Ratio Test</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Df.diff</th>
<th style="text-align: right;">LogLik.diff</th>
<th style="text-align: right;">Chisq</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: right;">-3</td>
<td style="text-align: right;">-131.51</td>
<td style="text-align: right;">263.02</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Since the given p-value is 0 which is clearly less than 0.05, hence, the null hypothesis is rejected, that adding the predictors is better than the null model with no predictors at all.</p>
<p><strong>Lipsitz Test</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lipsitz.test</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Lipsitz goodness of fit test for ordinal response models

data:  formula:  passengerClass ~ survived + sex + age
LR statistic = 16.42, df = 9, p-value = 0.05861</code></pre>
</div>
</div>
<p>Since the p-value is greater than 0.05, we do not reject the null hypothesis. The model is adequately fitting the ordinal data.</p>
<p><strong>Accuracy</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>predicted_data <span class="ot">&lt;-</span> <span class="fu">predict</span>(fit, testing_data, <span class="at">type =</span> <span class="st">"class"</span>)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">confusionMatrix</span>(testing_data<span class="sc">$</span>passengerClass, predicted_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<table class="table">
<caption>Confusion Matrix and Statistics by Class of Titanic Survival Data</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th colspan="3" style="text-align: center;">Reference</th>
<th style="text-align: center;">Accuracy</th>
<th colspan="3" style="text-align: center;">Sensitivity</th>
<th colspan="3" style="text-align: center;">Specificity</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Prediction</td>
<td style="text-align: left;">1st</td>
<td style="text-align: left;">2nd</td>
<td style="text-align: left;">3rd</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">C1</td>
<td style="text-align: center;">C2</td>
<td style="text-align: center;">C3</td>
<td style="text-align: center;">C1</td>
<td style="text-align: center;">C2</td>
<td style="text-align: center;">C3</td>
</tr>
<tr class="even">
<td style="text-align: right;">1st</td>
<td style="text-align: center;">41</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">16</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: right;">2nd</td>
<td style="text-align: center;">13</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">39</td>
<td style="text-align: center;">0.61</td>
<td style="text-align: center;">0.59</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0.61</td>
<td style="text-align: center;">0.89</td>
<td style="text-align: center;">0.75</td>
<td style="text-align: center;">0.79</td>
</tr>
<tr class="even">
<td style="text-align: right;">3rd</td>
<td style="text-align: center;">15</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">86</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
<p><strong>Confusion Matrix</strong></p>
<p>For the 1st class, the model correctly predicted 41 passengers as 1st class when the actual class of the passengers are 1st class. Moreover, there are 16 incorrectly predicted as 3rd class. For the 2nd class, the model correctly predicted only 1 passenger as being in the 2nd class. It misclassified 13 passengers who were actually in 1st class as being in 2nd class, and 39 passengers who were in 2nd class were mistakenly classified as being in 3rd class. This shows a significant misclassification error for 2nd class passengers. Lastly, for the 3rd class, the model correctly predicted 86 passengers as the actual third class, while misclassifying the 15 passengers as the 1st class. The misclassification error in the prediction for 2nd class may result in significant loss of accuracy in the prediction power of the model. The same can be applied for the incorrect prediction for the other classes.</p>
<p><strong>Accuracy</strong></p>
<p>The overall model accuracy is 0.61. The accuracy is low because of the misclassification resulted in the confusion matrix. One of the possible contribution for this is that due to the disproportionate number for each category of the dependent variable as what is performed in the descriptive statistic earlier.</p>
<p><strong>Sensitivity</strong></p>
<p>For the first class, the sensitivity is 0.59, meaning the model correctly identified 59% of all actual 1st class passengers as 1st class. The sensitivity in class 2 is 1.0 implies the model perfectly identified all passengers who were actually in 2nd class, although from the confusion matrix, it appears there was an issue with only 1 passenger correctly identified. Lastly, the sensitivity is 0.61 for the third class indicating that 61% of actual 3rd class passengers were correctly predicted as 3rd class by the model.</p>
<p><strong>Specificity</strong></p>
<p>The specificity is 0.89 for the 1st class, which means the model correctly identified 89% of passengers who were not in 1st class.For the 2nd class, the specificity is 0.75, indicating that 75% of the passengers not belonging to 2nd class were accurately identified as not being 2nd class. Lastly, for the 3rd class, with a specificity of 0.79, the model correctly identified 79% of the non-3rd class passengers.</p>
<p>Now that the model diagnostics are finished, the subsequent section involves refining the model by eliminating variables that are not statistically significant. This step will help determine if the model’s fit has improved. Additionally, the upcoming section will compare the changes in coefficients, intercepts, interpretations, and model diagnostics.</p>
</section>
<section id="removing-insignificant-variable-1" class="level3">
<h3 class="anchored" data-anchor-id="removing-insignificant-variable-1">Removing Insignificant Variable</h3>
<p>This section contains the comparison of the original ordinal logistic model of the <code>TitanicSurvival</code> data set with the remodeled version where the <code>sex</code> variable is removed. The full output of the modelling, inference, and assessment of the model of the remodeled version can be seen in the appendix.</p>
</section>
<section id="modeling-3" class="level3">
<h3 class="anchored" data-anchor-id="modeling-3">Modeling</h3>
<table class="table">
<caption>Comparison of Coefficients and Intercepts</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th colspan="4" style="text-align: center;">Original</th>
<th style="text-align: left;"></th>
<th colspan="4" style="text-align: center;">Remodeled</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">Value</td>
<td style="text-align: center;">Std. Error</td>
<td style="text-align: center;">t value</td>
<td style="text-align: center;">p value</td>
<td style="text-align: left;"></td>
<td style="text-align: center;">Value</td>
<td style="text-align: center;">Std. Error</td>
<td style="text-align: center;">t value</td>
<td style="text-align: center;">p value</td>
</tr>
<tr class="even">
<td style="text-align: right;">survivedyes</td>
<td style="text-align: center;">-1.751</td>
<td style="text-align: center;">0.184</td>
<td style="text-align: center;">-9.538</td>
<td style="text-align: center;">0</td>
<td style="text-align: left;"></td>
<td style="text-align: center;">-1.592</td>
<td style="text-align: center;">0.149</td>
<td style="text-align: center;">-10.683</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">sexmale</td>
<td style="text-align: center;">-0.275</td>
<td style="text-align: center;">0.181</td>
<td style="text-align: center;">-1.517</td>
<td style="text-align: center;">0.129</td>
<td style="text-align: left;"></td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
</tr>
<tr class="even">
<td style="text-align: right;">age</td>
<td style="text-align: center;">-0.066</td>
<td style="text-align: center;">0.005</td>
<td style="text-align: center;">-12.131</td>
<td style="text-align: center;">0</td>
<td style="text-align: left;"></td>
<td style="text-align: center;">-0.066</td>
<td style="text-align: center;">0.005</td>
<td style="text-align: center;">-12.154</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1st|2nd</td>
<td style="text-align: center;">-4.082</td>
<td style="text-align: center;">0.276</td>
<td style="text-align: center;">-14.774</td>
<td style="text-align: center;">0</td>
<td style="text-align: left;"></td>
<td style="text-align: center;">-3.848</td>
<td style="text-align: center;">0.226</td>
<td style="text-align: center;">-17.011</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">2nd|3rd</td>
<td style="text-align: center;">-2.688</td>
<td style="text-align: center;">0.253</td>
<td style="text-align: center;">-10.617</td>
<td style="text-align: center;">0</td>
<td style="text-align: left;"></td>
<td style="text-align: center;">-2.456</td>
<td style="text-align: center;">0.198</td>
<td style="text-align: center;">-12.377</td>
<td style="text-align: center;">0</td>
</tr>
</tbody>
</table>
<p>Table 25 compares coefficients from original and remodeled ordinal logistic regression models. In the remodeled model, ‘sexmale’ is removed due to its non-significant p-value. In the remodeled version, the coefficients slightly decreased, but continued to show significance. The intercepts for class transitions ‘1st|2nd’ and ‘2nd|3rd’ decreased, indicating clearer distinctions between classes in the remodeled model, which altogether suggests an enhanced model efficiency and interpretative clarity by excluding ‘sexmale’.</p>
<p><strong>Confidence Interval</strong></p>
<table class="table">
<caption>Comparison of Confidence Interval of Logit</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th colspan="3" style="text-align: center;">Original</th>
<th style="text-align: left;"></th>
<th colspan="3" style="text-align: center;">Remodeled</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">logit</td>
<td style="text-align: center;">2.5 %</td>
<td style="text-align: center;">97.5 %</td>
<td style="text-align: left;"></td>
<td style="text-align: center;">logit</td>
<td style="text-align: center;">2.5 %</td>
<td style="text-align: center;">97.5 %</td>
</tr>
<tr class="even">
<td style="text-align: right;">survivedyes</td>
<td style="text-align: center;">-1.7506</td>
<td style="text-align: center;">-2.11550</td>
<td style="text-align: center;">-1.3953</td>
<td style="text-align: left;"></td>
<td style="text-align: center;">-1.5917</td>
<td style="text-align: center;">-1.8866</td>
<td style="text-align: center;">-1.3022</td>
</tr>
<tr class="odd">
<td style="text-align: right;">sexmale</td>
<td style="text-align: center;">-0.2745</td>
<td style="text-align: center;">-0.6328</td>
<td style="text-align: center;">0.0772</td>
<td style="text-align: left;"></td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
</tr>
<tr class="even">
<td style="text-align: right;">age</td>
<td style="text-align: center;">-0.0657</td>
<td style="text-align: center;">-0.0765</td>
<td style="text-align: center;">-0.0553</td>
<td style="text-align: left;"></td>
<td style="text-align: center;">-0.0659</td>
<td style="text-align: center;">-0.0767</td>
<td style="text-align: center;">-0.0554</td>
</tr>
</tbody>
</table>
<p>The log odds of the independent variables shows a decreased in value in the remodeled version as illustrated in table 23. There is no zero included in the confidence interval asserting statistically significance in the remodeled version. The comparison of the two models, albeit with slight changes in the values maintained its significance.</p>
<table class="table">
<caption>Comparison of Confidence Interval of Odds Ratio</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th colspan="3" style="text-align: center;">Original</th>
<th style="text-align: left;"></th>
<th colspan="3" style="text-align: center;">Remodeled</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">OR</td>
<td style="text-align: center;">2.5 %</td>
<td style="text-align: center;">97.5 %</td>
<td style="text-align: left;"></td>
<td style="text-align: center;">OR</td>
<td style="text-align: center;">2.5 %</td>
<td style="text-align: center;">97.5 %</td>
</tr>
<tr class="even">
<td style="text-align: right;">survivedyes</td>
<td style="text-align: center;">0.1737</td>
<td style="text-align: center;">0.1206</td>
<td style="text-align: center;">0.2478</td>
<td style="text-align: left;"></td>
<td style="text-align: center;">0.2036</td>
<td style="text-align: center;">0.1516</td>
<td style="text-align: center;">0.2719</td>
</tr>
<tr class="odd">
<td style="text-align: right;">sexmale</td>
<td style="text-align: center;">0.7599</td>
<td style="text-align: center;">0.5311</td>
<td style="text-align: center;">1.0802</td>
<td style="text-align: left;"></td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
<td style="text-align: center;">-</td>
</tr>
<tr class="even">
<td style="text-align: right;">age</td>
<td style="text-align: center;">0.9364</td>
<td style="text-align: center;">0.9263</td>
<td style="text-align: center;">0.9462</td>
<td style="text-align: left;"></td>
<td style="text-align: center;">0.9362</td>
<td style="text-align: center;">0.9262</td>
<td style="text-align: center;">0.9461</td>
</tr>
</tbody>
</table>
<p>The comparison of the odds ratio and confidence interval shows a slight change in the values between the two models. The two models maintained a significant impact.</p>
<p><strong>Pseudo R-squared</strong></p>
<table class="table">
<caption>Comparison of Pseudo R-squared</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th colspan="3" style="text-align: center;">Pseudo R-Squared</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: center;">Original</td>
<td style="text-align: left;"></td>
<td style="text-align: center;">Remodeled</td>
</tr>
<tr class="even">
<td style="text-align: left;">McFadden</td>
<td style="text-align: center;">0.149588</td>
<td style="text-align: left;"></td>
<td style="text-align: center;">0.148262</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cox and Snell (ML)</td>
<td style="text-align: center;">0.270207</td>
<td style="text-align: left;"></td>
<td style="text-align: center;">0.268165</td>
</tr>
<tr class="even">
<td style="text-align: left;">Nagelkerke (Cragg and Uhler)</td>
<td style="text-align: center;">0.307667</td>
<td style="text-align: left;"></td>
<td style="text-align: center;">0.305342</td>
</tr>
</tbody>
</table>
<p>Comparing the Pseudo R-squared between the two models, a slight changes occured, particularly slight decrease can be seen in the remodeled version This is the case because the <code>sex</code> variable has an association with the dependent variable, hence, when it is removed in the remodeled version, the values of R2 decreased.</p>
<p><strong>Likelihood Ratio Test</strong></p>
<table class="table">
<caption>Comparison on LRT</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Df.diff</th>
<th style="text-align: left;">LogLik.diff</th>
<th style="text-align: left;">Chisq</th>
<th style="text-align: left;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Original</td>
<td style="text-align: left;">-3</td>
<td style="text-align: left;">-131.51</td>
<td style="text-align: left;">263.02</td>
<td style="text-align: left;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Remodeled</td>
<td style="text-align: left;">-2</td>
<td style="text-align: left;">-130.34</td>
<td style="text-align: left;">260.69</td>
<td style="text-align: left;">0</td>
</tr>
</tbody>
</table>
<p>There is a decrease in the log likelihood difference, and the <span class="math inline">\(\chi^2\)</span> in the remodeled version since the <code>sex</code> variable is removed. Nevertheless, of the two LRTs, the null hypothesis is rejected, suggesting that adding the predictors is better than the null model with no predictors.</p>
<p><strong>Lipsitz Test</strong></p>
<table class="table">
<caption>Comparison on Lipsitz Test</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">LR Statistic</th>
<th style="text-align: left;">df</th>
<th style="text-align: left;">p value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Original</td>
<td style="text-align: left;">16.42</td>
<td style="text-align: left;">9</td>
<td style="text-align: left;">0.05861</td>
</tr>
<tr class="even">
<td style="text-align: left;">Remodeled</td>
<td style="text-align: left;">13.064</td>
<td style="text-align: left;">9</td>
<td style="text-align: left;">0.1597</td>
</tr>
</tbody>
</table>
<p>There is an increase in the p-value in the remodeled version. Even so, the two models are adequately fitting the ordinal data. The predictions of the model are the same or closely the same as the actual data.</p>
<p><strong>Accuracy</strong></p>
<table class="table">
<caption>Comparison of Confusion Matrix</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;"></th>
<th colspan="3" style="text-align: center;">Reference</th>
<th style="text-align: center;">Accuracy</th>
<th colspan="3" style="text-align: center;">Sensitivity</th>
<th colspan="3" style="text-align: center;">Specificity</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">Prediction</td>
<td style="text-align: left;">1st</td>
<td style="text-align: left;">2nd</td>
<td style="text-align: left;">3rd</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">C1</td>
<td style="text-align: center;">C2</td>
<td style="text-align: center;">C3</td>
<td style="text-align: center;">C1</td>
<td style="text-align: center;">C2</td>
<td style="text-align: center;">C3</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;">1st</td>
<td style="text-align: center;">41</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">16</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Original</td>
<td style="text-align: right;">2nd</td>
<td style="text-align: center;">13</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">39</td>
<td style="text-align: center;">0.61</td>
<td style="text-align: center;">0.59</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">0.61</td>
<td style="text-align: center;">0.89</td>
<td style="text-align: center;">0.75</td>
<td style="text-align: center;">0.79</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;">3rd</td>
<td style="text-align: center;">15</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">86</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: right;">1st</td>
<td style="text-align: center;">42</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">15</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Remodeled</td>
<td style="text-align: right;">2nd</td>
<td style="text-align: center;">16</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">37</td>
<td style="text-align: center;">0.59</td>
<td style="text-align: center;">0.58</td>
<td style="text-align: center;">NA</td>
<td style="text-align: center;">0.62</td>
<td style="text-align: center;">0.89</td>
<td style="text-align: center;">0.75</td>
<td style="text-align: center;">0.79</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: right;">3rd</td>
<td style="text-align: center;">15</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">86</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
<p>There are changes in the values in the confusion matrices, wherein the remodeled version fails to correctly predict the true positive of the 2nd class. This led to a decrease in the accuracy of the model from 0.61 to 0.59. Furthermore, this resulted in changes in Sensitivity.</p>
<table class="table">
<caption>Comparison on Residual Deviance and AIC</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Residual Deviance</th>
<th style="text-align: left;">AIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Original</td>
<td style="text-align: left;">1495.276</td>
<td style="text-align: left;">1505.276</td>
</tr>
<tr class="even">
<td style="text-align: left;">Remodeled</td>
<td style="text-align: left;">1497.609</td>
<td style="text-align: left;">1505.609</td>
</tr>
</tbody>
</table>
<p>Table 32 compares the Residual Deviance and AIC between the original and remodeled ordinal logistic regression models. The Residual Deviance shows a slight increase from 1495.276 in the original model to 1497.609 in the remodeled version, indicating a marginal decrease in model fit as it slightly fails to capture the data variability as effectively as the original. The AIC remains nearly unchanged, shifting from 1505.276 to 1505.609. These metrics indicate that the removal of the predictor has not significantly improved the overall efficiency and effectiveness of the model in explaining the variability in the data. Performing bootstrap analysis assesses if there is significant difference in the AIC of original and remodeled and the Residual deviance.</p>
<p><strong>Bootstrapping</strong></p>
<p>The bootstrap process involves resampling the original dataset 1000 times and for each sample. In calculating the difference between AIC and Residual Deviance, the statistic of the original is subtracted from the remodeled. The code of bootstrapping can be seen in the Appendix.</p>
<table class="table">
<caption>Bootstrap Statistics</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">original</th>
<th style="text-align: center;">bias</th>
<th style="text-align: center;">std. error</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">t1*</td>
<td style="text-align: left;">-0.3329053</td>
<td style="text-align: left;">-1.09505</td>
<td style="text-align: left;">3.537359</td>
</tr>
<tr class="even">
<td style="text-align: left;">t2*</td>
<td style="text-align: left;">-2.3329053</td>
<td style="text-align: left;">-1.09505</td>
<td style="text-align: left;">3.537359</td>
</tr>
</tbody>
</table>
<p>The table above is the bootstrap analysis performed in <code>R</code>, where the <span class="math inline">\(t1*\)</span> represents he difference in AIC, the <span class="math inline">\(t2*\)</span> is for the difference in Residual Deviance. The negative bias in both the AIC and Residual Deviance differences suggests that the bootstrap replications tend to produce smaller differences than those observed in the original data. The standard errors imply that there is a significant spread in the estimates of these differences across the bootstrap sample.</p>
<p>Removing non-statistically significant variables from an ordinal logistic regression model, can sometimes lead to a worsening of the model’s performance. This phenomenon may seem counterintuitive since it is generally recommended to simplify models by eliminating variables that do not contribute significant improvements. According to Agresti (2010), he discussed that excluding variables may not show immediate statistical significance but could still be influential. This was supported by Harrel (2001), noting that non-significant variables might still play crucial roles in the context of confounding or interacting effects. In the study of Hosmer, et al.&nbsp;(2013) about “Applied Logistic Regression”, they give caution against the indiscriminate removal of variables based solely on their p-values without considering their roles in the model’s architecture.</p>
<table class="table">
<caption>Bootstrap Confidence Interval</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Level</th>
<th style="text-align: center;">Basic</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(t1*\)</span></td>
<td style="text-align: left;">95 %</td>
<td style="text-align: center;">(-2.6513, 10.0923)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(t2*\)</span></td>
<td style="text-align: left;">95 %</td>
<td style="text-align: center;">(-4.651, 8.092)</td>
</tr>
</tbody>
</table>
<p>The inclusion of zero in the confidence intervals suggests that the differences in AIC and Residual Deviance are not statistically significant. This means that, with respect to these metrics, the remodeled model does not differ significantly from the original model. Removing variables did not significantly improve or worsen the model’s fit.</p>
</section>
</section>
<section id="conclusion-and-recommendation" class="level1">
<h1>Conclusion and Recommendation</h1>
<p>This report utilized ordinal logistic regression to examine two datasets: the decision-making process regarding graduate school applications among college juniors and the socio-economic factors affecting survival on the Titanic. Through model evaluations and diagnostics, including Pseudo R-squared values, Likelihood Ratio Tests, and other fit assessments, valuable insights were gathered into the influence of various predictors on ordered categorical outcomes.</p>
<p>For the graduate school application study, results underscored the significant role parental education and GPA play in influencing students’ likelihood of applying to graduate school. The study emphasized how these factors quantitatively affect students’ decision-making processes across different likelihood categories.</p>
<p>In the Titanic dataset analysis, the findings showed clear socio-economic divides in survival rates. It demonstrates that passenger class and age significantly influenced survival likelihood. Key findings indicated that survivors were more likely to be from higher social classes, highlighting the social stratification’s impact on survival probabilities. Moreover, older passengers were less likely to be in higher classes, potentially influencing their survival chances. This analysis not only provided statistical backing to historical accounts but also offered a deeper understanding of how these factors interacted under extreme circumstances.</p>
<p>Based on the findings from these analyses, the following recommendations are proposed:</p>
<ul>
<li><p>The additional of variables that relates well to the dependent variable that could affect the decision-making process for potential graduate students. Examples would be psychological factors or financial considerations. For historical datasets like the Titanic, extending the analysis to include crew data and comparing it with other maritime disasters could provide broader insights.</p></li>
<li><p>It is recommended to refine data handling and model fitting techniques, such as addressing any imbalance in class distributions within datasets or employing more sophisticated methods for handling missing data and outliers to improve model accuracy and reliability.</p></li>
</ul>
</section>
<section id="references" class="level1">
<h1>References</h1>
<p>Agresti, Alan. (2010). “Analysis of Ordinal Categorical Data”. Wiley Series in Probability and Statistics.</p>
<p>Archibald, T., &amp; Sloan, J. (2011). Titanic: The Real Story of the Construction of the World’s Most Famous Ship. Channel 4 Books.</p>
<p>Arfan, M., &amp; Sherwani, R. (2017, January 1). Ordinal Logit and Multilevel Ordinal Logit Models: An Application on Wealth Index MICS-Survey Data. Pakistan Journal of Statistics &amp; Operation Research, 13(1), 211-226. https://doi.org/10.18187/pjsor.v13i1.1801</p>
<p>Arı, E., &amp; Yıldız, Z. (2014). Parallel Lines Assumption in Ordinal Logistic Regression And Analysis Approaches. International Interdisciplinary Journal of Scientific Research, 1(3), 8-23.</p>
<p>Astin, A. W. (1984). Student involvement: A developmental theory for higher education. Journal of College Student Development, 25(4), 297-308.</p>
<p>Beesley, L. (2011). The Loss of the SS. Titanic: Its Story and Its Lessons. Hesperides Press.</p>
<p>Brant, R. (1990). Assessing Proportionality in the Proportional Odds Model for Ordinal Logistic Regression. Biometrics, 46(4), 1171–1178. https://doi.org/10.2307/2532457</p>
<p>Borooah, V. K. (2002). Logit and probit: Ordered and multinomial models. Thousand Oaks, CA: Sage.</p>
<p>Bowen, W. G., &amp; Bok, D. (1998). The Shape of the River: Long-Term Consequences of Considering Race in College and University Admissions. Princeton University Press.</p>
<p>Cox, D. R., and E. J. Snell. 1989. The Analysis of Binary Data, 2nd ed.&nbsp;London: Chapman and Hall.</p>
<p>Davison, A. C., &amp; Hinkley, D. V. (1997). Bootstrap Methods and Their Application. Cambridge University Press.</p>
<p>Efron, B., &amp; Tibshirani, R. J. (1994). An Introduction to the Bootstrap. Chapman &amp; Hall/CRC.</p>
<p>Ethington, C. A., &amp; Smart, J. C. (1986). Persistence to graduate education. Research in Higher Education, 24(3), 287-303.</p>
<p>Frey, B. S., Savage, D. A., &amp; Torgler, B. (2010). Behavior under extreme conditions: The Titanic disaster. Journal of Economic Perspectives, 25(1), 209-222.</p>
<p>Hall, W. (2014). Titanic: The Unfolding Story as Told by the Daily Mirror. Pavilion Books.</p>
<p>Hardin, J., &amp; Hilbe, J. (2007). Generalized linear models and extensions (2nd ed.). College Station, TX: Stata Press.</p>
<p>Harrell, Frank E. Jr.&nbsp;(2001). “Regression Modeling Strategies: With Applications to Linear Models, Logistic and Ordinal Regression, and Survival Analysis”. Springer Series in Statistics.</p>
<p>Hosmer, D.W., Lemeshow, S., &amp; Sturdivant, R.X. (2013). “Applied Logistic Regression”. Wiley Series in Probability and Statistics.</p>
<p>IBM. (2023, September 19). https://www.ibm.com/docs/en/spss-statistics/saas?topic=model-pseudo-r-square</p>
<p>Stuart R. Lipsitz &amp; Garrett M. Fitzmaurice &amp; Geert Molenberghs, 1996. “Goodness‐Of‐Fit Tests for Ordinal Response Regression Models,” Journal of the Royal Statistical Society Series C, Royal Statistical Society, vol.&nbsp;45(2), pages 175-190, June.</p>
<p>Long, J. S. (1997). Regression models for categorical and limited dependent variables. Thousand Oaks, CA: Sage.</p>
<p>McCullagh, P. (1980). Regression Models for Ordinal Data. Journal of the Royal Statistical Society. Series B (Methodological), 42(2), 109–142. http://www.jstor.org/stable/2984952</p>
<p>McCullagh, P., &amp; Nelder, J.A. (1989). Generalized linear models (2nd ed.). London: Chapman &amp; Hall.</p>
<p>McFadden, D. 1974. Conditional logit analysis of qualitative choice behavior. In: Frontiers in Economics, P. Zarembka, eds.&nbsp;New York: Academic Press.</p>
<p>McNulty K. Handbook of Regression Modeling in People Analytics: With Examples in R and Python. 1st edition. Chapman and Hall/CRC; 2021.</p>
<p>Mitrani, A., (2019, December 6). Evaluating Categorical Models II: Sensitivity and Specificity. Towards Data Science. https://towardsdatascience.com/evaluating-categorical-models-ii-sensitivity-and-specificity-e181e573cff8#:~:text=Sensitivity %20is%20the%20metric%20that,negatives%20of%20each%20available%20category</p>
<p>Nagelkerke, N. J. D. 1991. A note on the general definition of the coefficient of determination. Biometrika, 78:3, 691-692.</p>
<p>Perna, L. W., &amp; Titus, M. A. (2005). The relationship between parental involvement as social capital and college enrollment: An examination of racial/ethnic group differences. Journal of Higher Education, 76(5), 485-518.</p>
<p>Spigner, C. (2012). Age, social class and gender on the Titanic. Disaster Prevention and Management.</p>
<p>Tenny S, Hoffman MR. Odds Ratio. [Updated 2023 May 22]. In: StatPearls [Internet]. Treasure Island (FL): StatPearls Publishing; 2024 Jan-. Available from: https://www.ncbi.nlm.nih.gov/books/NBK431098/#</p>
<p>Tinto, V. (1993). Leaving College: Rethinking the Causes and Cures of Student Attrition. University of Chicago Press.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>